### ISSUE TITLE
Original message available on HermesResponse when it wasn't published

### ISSUE THREAD

**Issue by rafal-glowinski** [allegro/hermes#1008]
When HermesMessage cannot be published and all retries are exhausted, client returns `CompletableFuture<HermesResponse>` and we can query the `HermesResponse` to see if it was a successful publication or not.

I think it would be useful to be able to retrieve the message that was not published using some additional method: `HermesResponse.failedMessage()`. 

Since `HermesClient` is asynchronous, it would be cleaner to have one, default, way of getting the failed message than have everyone to bind it somehow to async execution context.

**Comment by jewertow** [comment]
Resolved in #1073.
