### ISSUE TITLE
Investigate and consolidate HTTP clients

### ISSUE THREAD

**Issue by cristaloleg** [allegro/hermes#1011]
Currently we're using 2 different HTTP clients in Hermes. It will be much easier for us to handle only 1 type.

**Comment by druminski** [comment]
Serial consumer uses Jersey HTTP client but Batch consumer uses Apache HTTP Client. Serial has much higher priority in Hermes and it works fine so we can try to use also Jersey HTTP Client in Batch consumer. However we have to be careful with this as we don’t want to break Serial Consumer.

**Comment by druminski** [comment]
Also we have to keep batch consumer timeouts configuration consistent with serial consumer.

**Comment by haridevelops** [comment]
can i have a look in to it ?

**Comment by cristaloleg** [comment]
@haridevelops sure

**Comment by druminski** [comment]
This issue is still open and available.

**Comment by piotrrzysko** [comment]
Resolved in #1620
