### ISSUE TITLE
Hermes works on OpenJDK 11

### ISSUE THREAD

**Issue by druminski** [allegro/hermes#1024]
Right now Hermes works on Java 8. We would like to update it to work with OpenJDK 11. 

On this fork/branch you can find changes which update Hermes to work with OpenJDK11: https://github.com/lukidzi/hermes/tree/upgrade_jdk_11

**Comment by grzesuav** [comment]
https://github.com/allegro/hermes/pull/1060

**Comment by jewertow** [comment]
Resolved in #1060.
