### ISSUE TITLE
HermesClientBasicRetryCondition should handle SocketTimeoutException

### ISSUE THREAD

**Issue by macieg** [allegro/hermes#1036]
https://github.com/allegro/hermes/blob/master/hermes-client/src/main/java/pl/allegro/tech/hermes/client/HermesClientBasicRetryCondition.java

is handling only 5xx and 408 errors. A socket timeout sounds like a reasonable exception to cover.

**Comment by macieg** [comment]
This change is pointless, isFailedExceptionally check includes SocketTimeoutException.

**Comment by cristaloleg** [comment]
👌
