### ISSUE TITLE
Header filters in Hermes-console

### ISSUE THREAD

**Issue by druminski** [allegro/hermes#1043]
Currently JSON and Avro filters can be added via Hermes-console. Thanks to #753 we can also add Header filters via REST API. Unfortunately, Header filters aren’t supported via GUI. It would be nice to have this support in Hermes-console. Furthermore, it should be enabled/disabled by configuration as not all environments have to support Headers filters.

**Comment by qrman** [comment]
Hi, can I take this one?

**Comment by cristaloleg** [comment]
@qrman sure, you can

**Comment by qrman** [comment]
@druminski Can you explain what do you mean by saying: `it should be enabled/disabled by configuration as not all environments have to support Headers filters`?

Should filtering section be visible only when some flag in configuration is set? Does Hermes (`SubscriptionEndpoint`) throw any exception when headers filters are set and environment doesn't support filtering?
