### ISSUE TITLE
Counter values summed from all zookeeper clusters

### ISSUE THREAD

**Issue by druminski** [allegro/hermes#1065]
Counters such as `published`, `delivered`, `discarded` are kept in zookeeper. Thanks to this their values aren't reset after Hermes restart. However, recently multi-zookeeper feature was introduced in Hermes allowing to have independent Hermes Zookeeper clusters per DC. Due to this, at the moment when a client sends a request about some topic or subscription metrics to hermes-management then it receives metrics only from a local zookeeper cluster but should receive a value summed from all zookeeper clusters.

Metric endpoints in hermes-management should sum up counter values from all zookeeper clusters.

**Comment by jewertow** [comment]
Resolved in #1071
