### ISSUE TITLE
Manually create consumer group/commit offsets on subscription creation

### ISSUE THREAD

**Issue by dankraw** [allegro/hermes#1081]
We could manually create consumer groups and commit their offsets to specified values (like current topic offsets) and at the same time have kafka's `auto.offset.reset` on consumers set to `earliest` (it would work with `latest` as well).
This way it would be safer to deal with offsets resetting that may happen when messages are removed due to data retention policies, but there are some stale offsets committed. In such cases some messages may be lost if consumer resets offsets to latest.

This can be implemented in consumers (when the subscription is still in pending state) or in management (IMO it's even better option as we control the subscription creation there and have access to all kafka clusters).

**Comment by jewertow** [comment]
I will take care of it.
