### ISSUE TITLE
Proposal: UI update

### ISSUE THREAD

**Issue by pwolaq** [allegro/hermes#1142]
Hello,

Have you thought about doing a complete UI rewrite? Bootstrap 3 with AngularJS is a bit outdated setup. Introducing modern library/framework would add several benefits eg. hot reloading or typescript support. Also, refreshed components would make hermes console more attractive.

Proposed setup:
- [React](https://reactjs.org/)
- [Typescript](https://www.typescriptlang.org/)
- [Ant Design](https://ant.design/docs/react/introduce)

If you are interested in migration I would be happy to help.

**Comment by platan** [comment]
Another reason to stop using AngularJS, according to https://docs.angularjs.org/misc/version-support-status:
> On July 1, 2018 AngularJS entered a 3 year Long Term Support period.
UPDATE (2020-07-27):
Due to COVID-19 affecting teams migrating from AngularJS, we are extending the LTS by six months (until December 31, 2021).

**Comment by druminski** [comment]
Hey Guys, yes we discussed about it and we agree with you that UI needs to be rewritten, although it's a bigger task which we are planning to do in the future.

**Comment by trombka** [comment]
I've been considering adding an extended HTTP gateway as an optional tool in the deployment of [Nussknacker](https://nussknacker.io). I think Hermes would fit well if it had some improvements and UI is the biggest one.
We do not use Hermes in production but have several deployments of Nu. In some of them, such a tool would be useful.
