### ISSUE TITLE
No way to clear HermesMock state

### ISSUE THREAD

**Issue by tfij** [allegro/hermes#1143]
Hi!
When running my test suite, I've encountered this situation. 
During first test - as a side effect - I've sent 1 event on hermes topic - it didn't matter to the test assertion. Next test also sends 1 event on the same topic - but this time - I want to assert on this event. This assertion failes, because I'm receiving events from previous test! 

Example test:
```groovy
def conditions = new PollingConditions(timeout: 10)

@After
@Before
void resetReceivedRequest() {
    hermesMock.resetReceivedRequest()
}

def "test 1"() {
    when:
    def x = myService.doSomething()

    then:
    x == 2
}

def "test 2"() {
    when:
    def x = myService.doSomething()

    then:
    conditions.eventually {
        assert hermesMock.query().allJsonMessagesAs("topicName", Map.class).size() == 1
    }
}
```
It looks like the asynchronous nature of hermes client causes events to arrive during "mid tests" time. I don't have any way to stop or to reset MockHermes event processing.

Adding sleep fixes the problem:
```groovy
void resetReceivedRequest() {
    sleep(10)
    hermesMock.resetReceivedRequest()
}
```
...but I'm not satisfied with this approach ;)

**Comment by druminski** [comment]
Hi Tomek,

The problem which you have described actually is in a hermesClient which by default is asynchronous. "test 1" doesn’t wait for the hermesClient sending event in a background thread to a hermes-mock. This the reason why in "test 2" you can receive 2 events instead od 1 in the hermes-mock.

I see two solutions for this problem:

1. Make hermes-client synchronous for the needs of your tests. To do this you will have to introduce custom implementation of HermesSender interface. It shouldn't be difficult as this interface has one method.

2. In @After/@Before cancel all tasks in hermesClient. Here is a snippet of code how you could do it using okhttp client.

```
