### ISSUE TITLE
Use frontend as endpoint for existing brokers

### ISSUE THREAD

**Issue by joncourt** [allegro/hermes#1155]
Hi,

Is there a way to use frontend in front of our existing brokers - with their own naming convention etc.. please?

We currently use the Kafka Rest Proxy for this but find it's a little rudimentary for our purposes. Most of our clients use the kafka clients except for our mainframe which cannot. I'm looking at frontend and am excited by the async and buffering capabilities i believe it has and would like to trial using it in place of kafka-rest proxy if that is possible.

Regards,
Jon

**Comment by dankraw** [comment]
Hello @joncourt 

We're happy to hear that you consider using Hermes. :]

As for using Hermes as the frontend for existing brokers:
You should be aware that Hermes maintains a custom hierarchical structure of groups and topics, plus there is a Kafka topic naming convention that relates to that structure.
If the current naming scheme doesn't fit and there's no way for it to conform Hermes, there are ways that you could provide a custom naming convention by overriding [KafkaNamesMappers ](https://github.com/allegro/hermes/blob/hermes-1.3.4/hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/kafka/KafkaConfiguration.java#L148) and [KafkaNamesMapperFactory](https://github.com/allegro/hermes/blob/hermes-1.3.4/hermes-common/src/main/java/pl/allegro/tech/hermes/common/di/CommonBinder.java#L87).

Another problem you might come across is plugging existing Kafka topics into Hermes. 
Probably you won’t be able to create a topic using hermes management if one already exists (with a corresponding name) in Kafka. 
If that happens, the solution is to create the appropriate node in zookeeper structure manually.

So there may not be an easy start for your use case as you’d have to dive into Hermes internals (modules, build system, dependencies used, like hk2, zookeeper, spring) and some unexpected problems may occur. But it should pay back in the future. :)

**Comment by joncourt** [comment]
Thank you for your excellent comments Daniel. I shall have a poke around in the guts as you say to see what we might be able to do.
