### ISSUE TITLE
Add metric type of Meter for filtered messages.

### ISSUE THREAD

**Issue by druminski** [allegro/hermes#1164]
Hermes for filtered messages only has following counter:

```
hermes.consumer.*.filtered.*.*.*.count
```

Besides this counter it would be nice to have metric type of meter, so we could easily see how many messages are filtered for a minute (m1_rate metric).

**Comment by jewertow** [comment]
I see that Hermes has also metric of type meter for filtered messages:
https://github.com/allegro/hermes/blob/master/hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/filtering/FilteredMessageHandler.java#L57
What's wrong with this meter?

**Comment by druminski** [comment]
@jewertow thanks for the verification. I wasn’t aware of this meter for filtered messages. In that case I called PR which removes dedicated counter. We don’t need it as `meter` also contains counter for filtered messages.
