### ISSUE TITLE
Unwrapping message content interface

### ISSUE THREAD

**Issue by druminski** [allegro/hermes#1185]
We would like to add an interface for [unwrapping message content](https://github.com/allegro/hermes/blob/d8dd808b48419acb2e141a40680210ca62ff7059/hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/kafka/KafkaSingleThreadedMessageReceiver.java#L156). The default implementation for this interface should be the same as is now. However it also should be easy to add [custom implementation](https://hermes-pubsub.readthedocs.io/en/latest/deployment/packaging/#consumers) for this interface via Hermes builder. 

Thanks to this interface one of our users will be able to introduce an implementation which reads 
 all message metadata from Kafka headers. It can be useful when you publish messages directly on Kafka and use only consuming module from Hermes.

**Comment by jewertow** [comment]
Resolved in #1189
