### ISSUE TITLE
shared shema registry

### ISSUE THREAD

**Issue by trombka** [allegro/hermes#1204]
Hi
I have a single environment consisting of Zookeeper, Kafka and Schema Registry. I want to run a few separate Hermes instances using _namespace feature_. With Kafka and ZK all works fine, but as for SR it seems that one cannot use a single instance with namespaced Hermes instances using the same topic names.
Is this supported?

**Comment by druminski** [comment]
Hi @trombka 

Currently Hermes doesn’t support _namespace_  feature for schema-registry as we didn’t need it so far. However, if you need it, then I don’t see any obstacles to add it on a flag.

To add this feature I see the following changes:

1. [SchemaService ](https://github.com/allegro/hermes/blob/08cbcaf9b8d1896c61bf4166511fb509a9476f0c/hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/schema/SchemaService.java) - when a proper flag is enabled then `SchemaService` wrapper aware of `KafkaNamesMapper` should be used. Here is an example of `KafkaNamesMapper` [usage](https://github.com/allegro/hermes/blob/8e43a2e1392cf6e2939238b38be14b5214137293/hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/kafka/service/KafkaBrokerTopicManagement.java#L37). 

2. There is a module called `hermes-schema` containing `SchemaRepository` class. It’s used in other hermes modules such as _frontend & consumers_. However it’s not aware od `KafkaNamesMapper`. Therefore, again when a proper flag is enabled then `SchemaRepository` wrapper aware of `KafkaNamesMapper` should be used.

Would like to introduce those changes or you prefer that we add them?

**Comment by trombka** [comment]
Of course someone from my team or I will contribute.

Since Kafka namespace can be defined per DC and there is just one Schema Registry URL per Hermes instance, I think we have to chose one of two options:

1. We make SR configuration per DC and use a flag like `schema.repository.use-kafka-namespace: true`.
2. We stay with a single SR url and use a flag like `schema.repository.namespace: <string>`

Am I right?

For the purpose of my team both options are fine, but which one would be better generally, what do you think?

**Comment by druminski** [comment]
Nice to read that you or your team member will implement it.

As for the introduced two options I think we only need the second one due to [the official recommendation](https://docs.confluent.io/current/schema-registry/multidc.html#sr-multi-datacenter-setup) about how SR should be used in multi-dc environment.
