### ISSUE TITLE
Configurable graphite reporting in frontend and consumer

### ISSUE THREAD

**Issue by m-bartosz** [allegro/hermes#1230]
It would be nice to have possibility to disable graphite reporting in frontend and consumer modules.

**Comment by piotrrzysko** [comment]
Hi, Hermes currently support it. Please take look at: https://hermes-pubsub.readthedocs.io/en/latest/configuration/metrics/#graphite (option `metrics.graphite.reporter`).

**Comment by piotrrzysko** [comment]
@m-bartosz I hope the suggested option resolves your problem. If not, please reopen this issue.
