### ISSUE TITLE
Configurable zookeekepr host address in management

### ISSUE THREAD

**Issue by m-bartosz** [allegro/hermes#1231]
It would be nice to have possibility to change zookeeper hostname or port via compose environment attributes in management module

**Comment by druminski** [comment]
Hermes-management is based on spring-boot and it allows to set configuration on many ways, for example via environment variable (more info about it in spring boot [documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.typesafe-configuration-properties.relaxed-binding.environment-variables))

In our docker example we use configuration over file as it was convenient for us.

Closing the issue.
