### ISSUE TITLE
Additional methods in HermesResponse

### ISSUE THREAD

**Issue by jewertow** [allegro/hermes#1233]
For now `HermesResponse` provides methods `isSuccess` and `isFailure`, but they are not sufficient to decide whether a client should retry a request or not, because in case of status code 400 (validation error) there is no sense to retry invalid request, but in case of 500 retrying makes sense.

It would be nice if `HermesResponse` had a methods to check whether a failure is temporary or not, for example `isRetryableFailure` and `isNonRetryableFailure`.

I suggest to name these methods retryable/non-retryable instead of server/client, because in case of read socket timeout Hermes frontend returns 408 status code and although this is a client error retrying makes sense.
Additionally Kafka uses similar naming convention (https://kafka.apache.org/0100/javadoc/index.html?org/apache/kafka/common/errors/RetriableException.html)

What do you think?

**Comment by druminski** [comment]
@jewertow hermes-client already has built-in retry mechanism which retries requests such as 5xx but not 4xx. isFailure() is called after retries policy is exhausted.
