### ISSUE TITLE
[Hermes-Console] Subscription view displays fixed headers as http header filters

### ISSUE THREAD

**Issue by milenakrawczyk** [allegro/hermes#1255]
Hermes-Console displays fixed headers as http header filters in subscription view. Instead, headers should have a dedicated pane in subscription view.

**Comment by druminski** [comment]
Subscription http filters and fixed http headers are two different functionalities, therefore fixed http headers should not be displayed in http filters view. As Milena written they should have a dedicated panel as current view is misleading. Screenshot revealing the problem:

<img width="1092" alt="Zrzut ekranu 2020-09-2 o 14 33 28" src="https://user-images.githubusercontent.com/4473056/91982252-3f062c80-ed2a-11ea-9592-2264be255609.png">

**Comment by mareckmareck** [comment]
I'll take care of it
