### ISSUE TITLE
Hermes-management publishes audit events about topics and subscriptions changes

### ISSUE THREAD

**Issue by druminski** [allegro/hermes#1260]
Hermes has [Auditor](https://github.com/allegro/hermes/blob/7907afb02503787760505cbfecca48369aa292f8/hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/Auditor.java) interface and its current implementation is [LoggingAuditor](https://github.com/allegro/hermes/blob/7907afb02503787760505cbfecca48369aa292f8/hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/audit/LoggingAuditor.java) which logs information about who and what changed on topics and subscriptions. For example when Hermes user creates or removes topic then LoggingAuditor logs information about this operation. It’s very valuable feature for us and we would like to extend it about emitting audit events to a provided URL (for us it will be Hermes topic). Thanks to this other service(s) can get information about topics and subscriptions changes.

Acceptance criteria:

1) Hermes-management publishes audit events about topics and subscriptions changes
2) Audit event should provide an information about what exactly have changed (diff of topic or subscription), what is the new state, and who submitted the change.
3) Configuration of publishing audit events allows to:
    - disable/enable publishing. By default it should be disabled.
    - set an URL on which audit events are published.

**Comment by DyspC** [comment]
Hello, 

I could probably work on this one but I need some information on how to run it locally in dev mode as I didn't see any gradle task for it. (eg. point a local dockerized kafka/zk/cache)

More related to this issue, I'd like to know if the settings can be the same one as the LoggingAuditor (audit.enabled), the config keys could be something like audit.log.enabled and audit.event.enabled but that means breaking changes for those who still use the old key.

The way I'd do this is by adding a primary CompositeAuditor bean that would hold a list of all other auditors in the spring registry and forward all calls to them. This way any future auditor implementation would be used as soon as spring knows of its existence.
The side effect would be deleting the Auditor.noOpAuditor as obsolete because not enabling any auditor would make the CompositeAuditor no-op itself.

**Comment by jewertow** [comment]
Hello @DyspC,
if you want to run Hermes locally you have few options to do this:
1) build packages and run: https://hermes-pubsub.readthedocs.io/en/latest/deployment/packaging/#packaging - but you have to provide dependencies (kafka, zookeeper)
2) run Hermes in docker with kafka, zookeeper and graphite: https://github.com/allegro/hermes/tree/master/docker
3) run Hermes in VM with kafka, zookeeper and graphite: https://github.com/allegro/hermes/tree/master/vagrant_provisioning
4) You can also look at my repository that I use to develop Hermes: https://github.com/jewertow/hermes-dev-environment - it provides docker-based environment (with Kafka, Zookeeper, Graphite and test subscriber) and scripts that automate building docker images with your local version of Hermes. Additionally there are scripts to quick setup groups, topics and subscriptions. This environment allows to deliver messages via HTTPS.

**Comment by druminski** [comment]
@DyspC In case of this issue I would write an integration test, for example in [TopicManagementTest](https://github.com/allegro/hermes/blob/1d1d1aa0c75d208ccae8f231039c52088b73f7f8/integration/src/integration/java/pl/allegro/tech/hermes/integration/management/TopicManagementTest.java#L32) class. The test should verify whether an audit event is sent to a remote service when topic or subscription was changed. In integration tests we use wiremock to verify whether events are sent to remote service. Take a look in [this assertion](https://github.com/allegro/hermes/blob/562b1623593a355747260b33b4677d906a3a6e1b/integration/src/integration/java/pl/allegro/tech/hermes/integration/PublishingTest.java#L69), we can do similar.

To speed up your development you can run single test by example command:

```
./gradlew iT --tests TopicManagementTest.shouldCreateTopic
```

If you need to debug your code then you can run following command:
```
./gradlew iT --tests TopicManagementTest.shouldCreateTopic --debug-jvm --info
```
then attach your IDE to remote JVM on 5005 port ([tutorial](https://docs.alfresco.com/5.2/tasks/sdk-debug-intellij.html)).

Happy Coding!

**Comment by DyspC** [comment]
Hello, 

I'm sorry I worked a bit on that and forgot about it, I added the CompositeAuditor and EventAuditor parts but couldn't go further than running the integration tests while sending events on webhook.site to check their content.

You'll find my branch there https://github.com/DyspC/hermes/tree/1260-audit-events and I can send it if you'd like to finalize it with a new iT

**Comment by druminski** [comment]
@DyspC please call a pull request with your changes and add in the description what is missing and that you don't have time to finish it. We will review it and decide what to do next. Thanks in advance for your contribution :)
