### ISSUE TITLE
Replace KafkaZkClient

### ISSUE THREAD

**Issue by druminski** [allegro/hermes#1261]
Hermes-management uses old KafkaZkClient ([here](https://github.com/allegro/hermes/blob/4c6cea41974f79fd8ad3e2a9dc5f5ed7a8ba15ea/hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/kafka/KafkaConfiguration.java#L98)) for operations such as:

* topic creation, removal and update
* read leader for partition
* read broker details 

The newest Kafka doesn’t expose zookeeper therefore we should replace KafkaZkClient in Hermes to something new. Hermes without direct use of Kafka Zookeeper is the first step to use Hermes with Kafka from Confluent Cloud.

Acceptance criteria:
* Hermes doesn’t use Kafka zookeeper

**Comment by mohammedtabish** [comment]
Hey, I would like to work on this, tried to get info on this and the JIRA ticker of KIP-500 which uses Metadata Quorum instead of the zookeeper is still unresolved and many subtasks pending so wanted to know does the newest version of Kafka 2.5.x doesn't use zookeeper? also can you please guide me on how to start working on this as I am new to open source contribution.

**Comment by druminski** [comment]
Hi @mohammedtabish 

This task is already taken by one of our team members. Sorry that we didn’t update it. However, please take a look on other [hacktoberfest tasks](https://github.com/allegro/hermes/labels/hacktoberfest) in Hermes project. Today, I will add few more. As for how start with open source, please follow our [contribution guide](https://github.com/allegro/hermes/blob/master/CONTRIBUTING.md).

**Comment by naartjie** [comment]
Would removing KafkaZkClient remove the dependency on Kafka's ZK entirely, and make Hermes ready for when Kafka finally drops ZK? Or are there other places where Hermes hits Kafka's ZK too?

**Comment by piotrrzysko** [comment]
Hi @naartjie, switching from `KafkaZkClient` to `KafkaAdminClient` will remove the dependency on Kafka's ZK from Hermes entirely. And as you said it will make Hermes ready for the famous [KIP-500](https://cwiki.apache.org/confluence/display/KAFKA/KIP-500%3A+Replace+ZooKeeper+with+a+Self-Managed+Metadata+Quorum).

**Comment by naartjie** [comment]
Thanks @piotrrzysko.

I suppose the WIP branch is here https://github.com/allegro/hermes/tree/1261-remove-zookeeper-clients.

**Comment by piotrrzysko** [comment]
Probably you are right, but I've noticed that this task is done in #1277 (released in [1.6.0](https://github.com/allegro/hermes/blob/master/CHANGELOG.md#160-15102020)). So I can close the issue. If you have other questions, please let us know at our [gitter](https://gitter.im/allegro/hermes?utm_source=notification&utm_medium=email&utm_campaign=unread-notifications).

**Comment by naartjie** [comment]
Oh nice, thanks for the the info and your quick response @piotrrzysko!!

We'll upgrade. I see now that we're still using an older version (1.5.2 I think) for some reason.
