### ISSUE TITLE
Audit logs for unsuccessful topic and subscription operations

### ISSUE THREAD

**Issue by druminski** [allegro/hermes#1267]
Hermes uses Audit interface to log information about who and what changed on topic or subscription. This interface is used mainly in TopicService and SubscriptionService classes and is called mostly at the end of an operation such as topic/subscription created, updated, deleted. When the operation is successful then we have the audit log about it. However, when the operation is unsuccessful then we don’t know who and what wanted to change. This issue is about to add audit logs before execution of any operation on topic and subscription. Thanks to this we will know who and what wanted to change even when the operation was unsuccessful. 

Acceptance criteria:
* Hermes-management logs who and what wanted to change on topic and subscription even if the operation was unsuccessful
* Hermes doesn’t send audit events for unsuccessful operation. Audit events is a future feature, see issue #1260

**Comment by DyspC** [comment]
Hi, 

I'm interested in looking into this enhancement, can you assign it to me?

From what I've read so far, this would mean adding preObjectSomething methods to the Auditor interface and calling them upon entering any non-readonly public method in both TopicService and SubscriptionService

This should not get in the way of the audit event feature as the new methods could be no-op on that Auditor implementation (or will you use the same implementation for both audit actions?)

**Comment by druminski** [comment]
Hi @DyspC,

Nice that you are interested to look into this enhancement. Your proposition of implementation sounds great. Happy coding!

**Comment by DyspC** [comment]
I'm almost done with the implementation and will send the PR around Thursday.

The beforeObjectUpdate is a bit tricky, do you want this to log the same format as objectUpdated ("User {} is updating {} {}. {}") or something around the lines "User {} is applying patch {patchData} to {objectClass} identified by [{pretty print of composite key}]"?

The latter can be applied when entering the methods and the other needs the patch to be applied first.

Also is (subscriptionName, topicName) the composite key that should be be logged for subscription updates or is it a double check and subscriptionName would be enough?

**Comment by druminski** [comment]
> I'm almost done with the implementation and will send the PR around Thursday.

Very nice 🚀 

> The beforeObjectUpdate is a bit tricky, do you want this to log the same format as objectUpdated ("User {} is updating {} {}. {}") or something around the lines "User {} is applying patch {patchData} to {objectClass} identified by [{pretty print of composite key}]"?

The present format in `LogginAuditor` has proven in the field, therefore I would use an analogous one. However, if you see it’s inconsistent/unclean solution for beforeObjectUpdate, then we can start with the second proposition of yours as it should be sufficient either.

> Also is (subscriptionName, topicName) the composite key that should be be logged for subscription updates or is it a double check and subscriptionName would be enough?

{objectClass} type of Subscription contains topic name and subscription name, so you just need to log old Subscription object. However, if you don’t have it at early stage, then I would create [SubscriptionName](https://github.com/allegro/hermes/blob/master/hermes-api/src/main/java/pl/allegro/tech/hermes/api/SubscriptionName.java) and log it. SubscriptionName is combined from TopicName and subscriptionName as they together create the composite key.

**Comment by DyspC** [comment]
Well the reason I think it could be unfit to log the same format is because it would need to find the existing object first, and then applying the patch.

If this operation fails there would be no before log and therefore the solution would be invalid.

I'll most likely use the second proposition now that I know there is a pojo for the subcription name
