### ISSUE TITLE
[Hermes-Console] button for copying schema of a topic

### ISSUE THREAD

**Issue by mareckmareck** [allegro/hermes#1279]
At the moment to copy schema of a topic in details view one must manually select whole schema by hand. Contrary to edit view user cannot use "select-all" to copy the schema.

To address this issue, it would be good to have a simple button enabling to copy the schema to clipboard on clicking. Probably the best place for that button would be either in the pane visible after opening "Message schema" in details view or directly on the "Message schema" bar.

**Comment by kacperkoza** [comment]
Hello, I would like to work on this one
