### ISSUE TITLE
Creating subscription error

### ISSUE THREAD

**Issue by robertwrobel** [allegro/hermes#1348]
Clicking on create subscriptions button on newest hermes version results in error.

![subscriptions](https://user-images.githubusercontent.com/85984599/122170345-c4546b00-ce7e-11eb-99cc-9efc05492916.png)

**Comment by druminski** [comment]
Thanks for reporting this issue. I've fixed it in #1351, tested in docker and released 1.9.1 Hermes version with the fix.
