### ISSUE TITLE
Repairing inconsistencies

### ISSUE THREAD

**Issue by piotrrzysko** [allegro/hermes#1385]
Hermes management has a mechanism used for detecting inconsistencies between data centers (implemented in #1296). We would like to extend this mechanism to not only detect inconsistencies but also repair them.

We can implement this in the current `Consistency` view (`Admin Tools` -> `Consistency`). It would be nice to have an option there allowing the admin to choose what version of a given inconsistent entity to apply to all data centers.

**Comment by moscicky** [comment]
Resolved in https://github.com/allegro/hermes/pull/1888
