### ISSUE TITLE
Consumers rate limiter docs

### ISSUE THREAD

**Issue by slomkarafa** [allegro/hermes#1436]
Hello,
Docs for `Consumers rate limiter` are outdated, for sure [Maximum rate negotiation](https://hermes-pubsub.readthedocs.io/en/latest/configuration/rate-limiting/#maximum-rate-negotiation) options are not available anymore. It is misleading, especially `consumer.maxrate.strategy` as `strict`, which was deleted in https://github.com/allegro/hermes/pull/1095 . Is it possible that someone with knowledge about that could update those docs? I will really appreciate it,
Thanks!

**Comment by piotrrzysko** [comment]
Solved in #1580.
