### ISSUE TITLE
Add possibility to skip events

### ISSUE THREAD

**Issue by piotrrzysko** [allegro/hermes#1562]
Currently, there is tribal knowledge that if someone wants to skip events, they need to order retransmission from a future date.

Maybe it would be useful and easier for users to just have a button "Skip events" (or something like that) that under the hood does exactly the same what "retransmission from a future date" does.

**Comment by sobelek** [comment]
Hey.
Can you explain to me what exactly does skipping events means?
Do I understand it correctly that if subscription have some lag than I can order retransmission from the future and events that were lagged will be discarded(skipped)?

**Comment by piotrrzysko** [comment]
> if subscription have some lag than I can order retransmission from the future and events that were lagged will be discarded(skipped)

This is a correct explanation.

**Comment by sobelek** [comment]
Great, I will tackle this soon.
