### ISSUE TITLE
Protect master branch from pushes without PR

### ISSUE THREAD

**Issue by piotrrzysko** [allegro/hermes#1565]
Currently, each release pushes directly to `master` a commit with a version update. An example: https://github.com/allegro/hermes/commit/7340b364c2f82642487545026bb95f2865feeb90. Because of that we cannot enable [branch protection](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule). We would like to either remove the need for the mentioned release commit or (if possible) somehow exclude releases from the branch protection rules.

**Comment by piotrrzysko** [comment]
I think that just disabling the version update in the mentioned files is not enough because the version number provided in `mkdocs.yaml` is used here: https://hermes-pubsub.readthedocs.io/en/latest/ (top right corner).

In my opinion, we can stop pushing release commits if we: 
* find an alternative way of delivering the version number to the documentation
* confirm that the `version` field from `package.json` is not used anywhere

**Comment by piotrrzysko** [comment]
Regarding the documentation, please take a look at [axion-release-plugin](https://github.com/allegro/axion-release-plugin) and their documentation https://axion-release-plugin.readthedocs.io/en/latest/. It looks like they somehow fetch version numbers without pushing release commits.

**Comment by kasmar00** [comment]
I need to correct by previous comment.
I thought that RTD is triggered somehow in release github action, but actually it just generates based on push to master. If the first would be the case, I would propose to add version to the two in release workflow, not commit them but use them in building, but given how RTD works, I don't see a quick way to make it happen.
If anyone has an idea how to make it work, feel free to work on this issue.

**Comment by kasmar00** [comment]
As discussed with @piotrrzysko in DM, I will resolve this task in two stages. First: migrate to mkdocs material theme - which axion uses and it provides an automatic way to fetch relaease number, and in second stage pushin a commit with updated versions will be removed.
