### ISSUE TITLE
Bump apache curator version in hermes

### ISSUE THREAD

**Issue by szczygiel-m** [allegro/hermes#1578]
currently hermes is using version [2.12.0](https://github.com/allegro/hermes/blob/master/build.gradle#L64), which was released Mar 01, 2017, newer versions have been released since then, so we would like hermes to use the newer one - l[ink to mvn repository](https://mvnrepository.com/artifact/org.apache.curator/curator-framework)

**Comment by kirsteend** [comment]
@szczygiel-m I'd like to work on this if you are still looking for contributors 
Thanks!

**Comment by szczygiel-m** [comment]
@kirsteend nice to hear that 😄 happy coding, i saw in the code that You may need to get rid of `Reaper` class from curator framework - please take a look at this [link](https://www.javadoc.io/doc/org.apache.curator/curator-recipes/4.2.0/org/apache/curator/framework/recipes/locks/Reaper.html)
