### ISSUE TITLE
Add checkstyle for unit tests

### ISSUE THREAD

**Issue by piotrrzysko** [allegro/hermes#1599]
In #1577 we introduced checkstyle for the production code. This time we want to do the same for the unit test code. The scope of this task:
* Invoke `checkstyleTest` (this is a gradle task that already exists) in [the GitHub action responsible for running checkstyle](https://github.com/allegro/hermes/blob/master/.github/workflows/checkstyle.yml#L27).
* Include a report generated by checkstyle for the unit test code in [the reviewdog check](https://github.com/allegro/hermes/blob/master/.github/workflows/checkstyle.yml#L32).
* Fix all violations reported by checkstyle.

**Comment by arrekb** [comment]
Hi, could you assign me?
