### ISSUE TITLE
Add checkstyle for benchmarks

### ISSUE THREAD

**Issue by piotrrzysko** [allegro/hermes#1601]
In #1577 we introduced checkstyle for the production code. This time we want to do the same for the benchmarks code. The scope of this task:
* Invoke `checkstyleJmh` (this is a gradle task that already exists) in [the GitHub action responsible for running checkstyle](https://github.com/allegro/hermes/blob/master/.github/workflows/checkstyle.yml#L27).
* Include a report generated by checkstyle for the benchmarks code in [the reviewdog check](https://github.com/allegro/hermes/blob/master/.github/workflows/checkstyle.yml#L32).
* Fix all violations reported by checkstyle.

**Comment by iremugurlu** [comment]
Hey, I'm interested. Can you assign this one to me?
