### ISSUE TITLE
EventAuditor should not ignore exceptions

### ISSUE THREAD

**Issue by piotrrzysko** [allegro/hermes#1605]
Currently, [EventAuditor](https://github.com/allegro/hermes/blob/master/hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/audit/EventAuditor.java) ignores all exceptions thrown while sending change notifications. It turns out that these notifications are valuable for systems integrated with Hermes. Therefore, instead of silently ignoring exceptions, we should retry a failed request first (it looks like we currently do not do this), and if retrying does not help we should propagate the exception to the user.

Additionally, for consistency with other places where `Auditor` is used, on the topic creation path, we should invoke the [objectCreated](https://github.com/allegro/hermes/blob/8707e95df86ebeaf78444efa3a0eb2eed3eb227a/hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/TopicService.java#L344) method after successfully completing the [`CreateTopicRepositoryCommand`](https://github.com/allegro/hermes/blob/8707e95df86ebeaf78444efa3a0eb2eed3eb227a/hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/TopicService.java#L350) instead calling it only when a topic has been created in Kafka.

**Comment by PhilippFr** [comment]
Taking a look on this 👍
