### ISSUE TITLE
ERROR when deploying Hermes: in gradle Step

### ISSUE THREAD

**Issue by emartinrda** [allegro/hermes#1642]
Hello, I'm getting the next error (screenshot attached below) when running "docker-compose up", don't know why doesn't find the file, I've downloaded the full project (https://github.com/allegro/hermes), any ideas?

```
A problem occurred evaluating root project 'hermes'.
> java.io.FileNotFoundException: /home/gradle/src/config (Is a directory)
```

I'm executing "docker-compose up" command inside hermes-master/docker directory as shown in screenshot.

![image](https://user-images.githubusercontent.com/22156660/206713218-06a567e5-872f-4d75-966b-72ce9956da6a.png)

**Comment by szczygiel-m** [comment]
we weren't able to reproduce this problem, closing
