### ISSUE TITLE
Remove TopicFieldSchemaSource* related code

### ISSUE THREAD

**Issue by pbetkier** [allegro/hermes#171]
`TopicFieldSchemaSourceProvider` and `TopicFieldSchemaSourceRepository` are obsolete now that we have a proper Zookeeper-based implementation. We can remove this implementation together with `messageSource` field in `Topic` to clean things up.

Requires that we have migrated our existing schemas to a new destination.

**Comment by adamdubiel** [comment]
@pbetkier did you clean it up while working on Avro schema versions?
