### ISSUE TITLE
Add better support to avro schema textfield in hermes-console

### ISSUE THREAD

**Issue by szczygiel-m** [allegro/hermes#1737]
Recently we have introduced new hermes console written in vue - https://github.com/allegro/hermes/pull/1697 
Old hermes-console had a functionality to show avro schema in a preety way, it was introduced in this PR - https://github.com/allegro/hermes/pull/1434 
Also schema editor such as one introduced in this PR would be great - https://github.com/allegro/hermes/pull/1407 
We would like to add such improvements in the new hermes-console 😄

**Comment by straburzynski** [comment]
I can take a look on auto formatting and highlighting feature in schema editor.

**Comment by szczygiel-m** [comment]
Nice to hear that! To precise - we are currently developing new hermes-console at the branch `hermes_console_vue`, but in a few weeks we would merge it to the master without squash, so that each contributor would be listed 😄

**Comment by straburzynski** [comment]
> Old hermes-console had a functionality to show avro schema in a preety way, it was introduced in this PR - https://github.com/allegro/hermes/pull/1434

Hi, I'm just letting you know that I started working on Avro schema viewer component, should be done soon.
