### ISSUE TITLE
Implement filtering subscription list in topic view

### ISSUE THREAD

**Issue by kszapsza** [allegro/hermes#1740]
Recently we have introduced new hermes console written in vue - https://github.com/allegro/hermes/pull/1697
It would be nice to have posibility to filter topic's subscriptions list on Topic view (by subscription name, by its status).

`hermes-console-vue/src/views/topic/subscriptions-list/SubscriptionsList.vue`

**Comment by carlosfrodrigues** [comment]
Hi, I'm interested in this one.
Could you assign for me :)

**Comment by szczygiel-m** [comment]
Hi, nice to hear that 😄 assigned
