### ISSUE TITLE
Add monitoring for Executor Services using micrometer ExecutorServiceMetrics

### ISSUE THREAD

**Issue by faderskd** [allegro/hermes#1748]
Currently we have `ExecutorMetrics` class for measuring executors in Hermes. Some of the executors are not measured at all. Micrometer has a `ExecutorServiceMetrics` class which already have similar functionality. We would like to measure every executor service in Hermes using this micrometer class.

**Comment by michal494** [comment]
I will be working on this issue during Hacktoberfest ;)

**Comment by michal494** [comment]
The pull request with the implementation of the refactor is ready for review: https://github.com/allegro/hermes/pull/1824
