### ISSUE TITLE
Add autocomplete functionality to "Message content filters" on subscription form

### ISSUE THREAD

**Issue by qrman** [allegro/hermes#1749]
#Hacktoberfest:

We would like to implement autocomplete functionality while writing avro path in Message content filters section in subscription form.

That would simplify adding new filters for events.

**Comment by straburzynski** [comment]
Hi, I'd like to try with this one 🙂

**Comment by szczygiel-m** [comment]
Nice to hear that 😄 in case of any questions/problems feel free to ask
