### ISSUE TITLE
Migrate to non-deprecated Apache Curator APIs

### ISSUE THREAD

**Issue by moscicky** [allegro/hermes#1886]
There are a couple of places which use deprecated Curator APIs, e.g. transactions and PathChildrenCache. Migrate them to new APIs

**Comment by szczygiel-m** [comment]
Rewrite API related to transactions should be easy, and it can be done during hacktoberfest.

Code related with `HierarchicalCache` class is a little bit harder, and it can be done in a separate PR.

**Comment by Anarak404** [comment]
Hi, can I work on this issue?

**Comment by szczygiel-m** [comment]
Sure, assigned 😄 If You have any questions, feel free to ask
