### ISSUE TITLE
Preview topic head

### ISSUE THREAD

**Issue by Kornel** [allegro/hermes#195]
Would be awesome to see in hermes frontend the latest message in the queue.

I'd like to preview what's currently on top of kafka without having to access kafka directly. It doesn't necessarily have to be the "very top" message.

**Comment by adamdubiel** [comment]
Could it be some cached value refreshed i.e. once every 10 min? Reading head each time might not be too smart :) In general publisher should provide some schema (and we have means for this in Hermes), but i suppose you have no such option :P

**Comment by Kornel** [comment]
Of course, every x min is fine, that's what I meant by not the very top :)

**Comment by adamdubiel** [comment]
This issue will be implemented starting Monday. Some additional design notes below.

* this process is *not critical* and should not block or have any other ill effects on sending messages to Kafka
* we should capture one or two messages per one or two minutes and save them in ZK in topic structure (similar to last undelivered message on subscription end)
* this needs to be optional, so it can be enabled only on debuggable environments (test/dev) and disabled by default
* message should be captured before conversion (i.e. capture JSON not Avro)

**Comment by Kornel** [comment]
This is a great feature for topics without a schema. For topics with a schema, I don't think it is necessary.

**Comment by adamdubiel** [comment]
We want to use it also as a way to debug schema conversion.

**Comment by tmmi** [comment]
This experimental feature added.
