### ISSUE TITLE
Broken image link in docs

### ISSUE THREAD

**Issue by bieli** [allegro/hermes#3]
Here http://hermes-pubsub.readthedocs.org/en/latest/contents/overview/01_architecture.html#hermes-consumers is problem with rendering image named "/_static/consumer_state_machine.png". Image is available here: http://hermes-pubsub.readthedocs.org/en/latest/_static/consumer_state_machine.png

**Comment by adamdubiel** [comment]
I just had to rebuild docs after @vi4m pull request, works fine now. Thanks!
