### ISSUE TITLE
image allegro/hermes-consumers not found

### ISSUE THREAD

**Issue by tycho01** [allegro/hermes#30]
Following the [guide](http://hermes-pubsub.readthedocs.org/en/latest/contents/tutorials/01_getting_started.html):

```
./run.sh
Starting docker_kafka_1...
Creating docker_consumers_1...
Pulling image allegro/hermes-consumers:latest...
Pulling repository allegro/hermes-consumers
[...]
Error: image allegro/hermes-consumers:latest not found
```

I also had to remove the 'distZip' parameter from `build.sh` to prevent another error (on there being no such task)...

As the error stated though, I can't find hermes-related images in [allegro's Docker repository](https://registry.hub.docker.com/repos/allegro/).

I noticed there were already local Dockerfiles that corresponded to the ones it can't find online, so I tried building images using those:

```
$ docker build Dockerfile-frontend
FATA[0000] The Dockerfile (Dockerfile) must be within the build context (Dockerfile-frontend) 
```

I must concede I'm relatively new to Docker, but I'm not sure if I'm missing an easy way to address these issues... I'd appreciate any help! :)

**Comment by adamdubiel** [comment]
Hi, could you checkout `hermes-0.7.1` tag and try it again? I guess i messed up docker images. We plan on publishing official docker images in near future.

**Comment by tycho01** [comment]
`hermes-0.7.1` built okay! Thanks!

**Comment by adamdubiel** [comment]
I will leave this issue open, so i can fix dockers in current release ;) Let us know if Hermes works for you.

**Comment by tycho01** [comment]
Okay, tried going through the rest of the tutorial page now... perhaps I should make a new thread for that though, since the build/run process seemed to work out okay. Thanks for the help so far.
