### ISSUE TITLE
Support overriding configuration options via environment variabls

### ISSUE THREAD

**Issue by sslavic** [allegro/hermes#308]
Please support overriding ideally all configuration options (e.g. port to which apps like hermes fronted bind to) using environment variables.

**Comment by adamdubiel** [comment]
Hi, we use [Archaius](https://github.com/Netflix/archaius/wiki/Getting-Started) to manage configuration for us. Currently we don't plan to migrate it to any other solution. May i ask whats your usecase?

**Comment by sslavic** [comment]
Trying to deploy Hermes Frontend to Cloud Foundry, port is dynamically assigned, app has to bind to it otherwise is considered as down. Would have to generate file on startup, to dump env vars to appropriate properties file.

Some other technologies support Archaius and still allow configuration property overrides through environment variables and Java system properties, e.g. http://cattle.readthedocs.org/en/latest/config/cattle-config.html and http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html#_external_configuration_archaius

I'm not sure if this is native Archaius feature, if appropriate APIs are used, or is it just something that these technologies had to add on top.

As workaround, will have to fork Hermes, at least as temporary solution; maybe evaluate using Archaius.

**Comment by adamdubiel** [comment]
I checked how we do it on Mesos, and we use overriding configuration via command line:

```
./hermes-frontend -Dfrontend.port=$PORT0
```

I guess this might work also in your case. I will take a look at the links you sent me.

**Comment by sslavic** [comment]
It worked! Passed custom config parameters as HERMES_FRONTEND_OPTS env var value; one of config params was -Dfrontend.port whose value referenced PORT env var.

Thank you very much Adam!

**Comment by adamdubiel** [comment]
Nice to hear it :) Let us know if you have any more problems or questions, i will be glad to answer them. We are also rolling out new documentation which i think is much more helpful than the old one, you can preview it here: http://hermes-pubsub.readthedocs.org/en/new-documentation/

**Comment by sslavic** [comment]
Thanks, discovered new documentation earlier - old one has some broken links or something, e.g. user documentation links are returning "This page does not exist yet", then I noticed version can be switched from latest to new-documentation. Thanks anyway for sharing!

**Comment by adamdubiel** [comment]
I will relevant documentation.
