### ISSUE TITLE
User can specify filter for outgoing events

### ISSUE THREAD

**Issue by adamdubiel** [allegro/hermes#312]
Consumers module should allow on specifying outgoing events filter. This expression would allow on writing simple matchers. Consumers sends only events that match the query.

* how to define filter language? JSON Path? What about Avro?
* how complicated can query be? i think for now simple `field_path == value` should be enough

**Comment by arciuchm** [comment]
I've been thinking about using an XPath expression that should evaluate to boolean. If true, the event goes out to the subscriber. This approach would work for Avro messages as well, if applied after convertion to JSON (I know, possibly unnecessary convertion).

**Comment by arciuchm** [comment]
Yes, JSON Path evaluating to boolean should be fine and it doesn't restrict the complexity of the query. It could be also applied to Avro messages, after the (possibly unnecessary, I know) convertion to JSON.

**Comment by mkuthan** [comment]
I found avro path extractor in kite-sdk project. It might be a good starting point.
https://github.com/kite-sdk/kite/blob/3974e2006d7de3af3453701b387f9ff4a0e6f61a/kite-morphlines/kite-morphlines-avro/src/main/java/org/kitesdk/morphline/avro/ExtractAvroPathsBuilder.java

**Comment by sslavic** [comment]
Would be nice if filter logic is plugable.

**Comment by martido** [comment]
Hi guys,

have you also thought about providing a more general filter mechanism? So not only checking against a query, but allowing arbitrary logic? Let me maybe explain our current situation in more detail.

Before a message is sent to the subscriber we have to check if it is allowed to see the data contained in the message. Currently this information is stored in a separate system and we have to make an external service call to get it. We've added a couple of optimizations so that we don't have to make that call for each and every message, but in the end we have to make it once in a while (there's unfortunately no way yet for us to get this information asynchronously). So for us it would be nice if we could plugin an arbitrary logic before sending the message to the subscriber. Ideally, the generic filtering mechanism would also tie in with the existing retry mechanism in case of errors because for example we wouldn't want to drop a message just because of network hiccups.

Do you think it's feasible to add something like this to Hermes?

**Comment by adamdubiel** [comment]
Of course it is feasible. I imagine it would be some kind of filter chains. Out of box you only get one filter, which is query-based-filter, but you could plug your own implementations to achieve something more sophisticated, while still keeping default behavior.

**Comment by adamdubiel** [comment]
Just an update: we will be working on this issue starting tomorrow.

**Comment by arciuchm** [comment]
This could be useful: https://github.com/wandoulabs/avpath

**Comment by martido** [comment]
Very nice that you started working on the feature!

I'd like to mention an additional thing that would be useful for us. In our case, for filtering outgoing events, we would need additional information that is available at subscription time. That is, a consumer would provide this information together with the subscription and we could use it to filter events. So we thought about extending Subscription to add a generic metadata field to it. A Subscription would then look like the following:

```
{
    "endpoint": "http://example.com",
    "supportTeam": "myTeam",
    "metadata": {
        "key": "value"
    }
}
```

To quickly try this out we added a `private Map<String, String> metadata` field to Subscription. It worked very well. Have you thought about this before? If you are willing to add something like this to Hermes we could also create a pull request or so.

**Comment by adamdubiel** [comment]
I must say I'm not a big fan of such unstructured data :) I don't know how the implementation will go, but we will try to come up with some solution that will suite your needs. We need to extend Subscription model somehow to pass the filter query anyway.

**Comment by fkowal** [comment]
How about using nashorn? Users would write a Javascript function to do the filtering.

**Comment by adamdubiel** [comment]
No, adding any type of scripting is not an option here - we don't need the overhead. And it would add no value for more complicated filters, like authorizing stuff (which needs some remote calls & cache).

**Comment by fkowal** [comment]
You could all kind of complex filter logic. Remote calls would not be a problem, u can call Java apis from nashorn its just a matter what Java objects you bind/pase to the javascript context. Overhead yes probably. 4k calls per s if i remember correctly from this prez http://www.infoq.com/presentations/template-spring-boot-nashorn?utm_source=infoqWeeklyNewsletter&utm_medium=WeeklyNL_EditorialContent_java&utm_campaign=03012016news

**Comment by adamdubiel** [comment]
I know what are the possibilities, but this is a crucial, pubsub system and
i would not want to give my users a chance to destroy it by some wierd
calls.

As to the overhead: scripting is just not worth it, when i can have
specialized operations on Avro byte stream instead of some probably
string/json logic. Imagine writing a script which does remote calls and
operates on byte arrays.

And there is a question of leaking a lot of APIs to the enduser. So, once
again, scripting is a no go.

**Comment by martido** [comment]
@adamdubiel Sounds good! If we were able to pass some information along with the Subscription that we could then use in some custom filtering logic, it would be great.
