### ISSUE TITLE
Support https protocol

### ISSUE THREAD

**Issue by sslavic** [allegro/hermes#313]
Hermes currently doesn't allow subscribers/consumers to be https endpoints, only http and jms - probably this https://github.com/allegro/hermes/blob/master/hermes-api/src/main/java/pl/allegro/tech/hermes/api/constraints/EndpointAddressValidator.java validation prevents https subscribers to register. Please consider allowing https endpoints as well, even if as a feature flag which is off by default.

**Comment by adamdubiel** [comment]
It's bit more complicated than just validation, but not too hard either. I suppose you would want to have a way to specify truststore (so we don't accept selfsigns)?

**Comment by sslavic** [comment]
Initially no custom truststore support needed, only default Java truststore (jssecacerts if it exists, otherwise cacerts), so no self-signed certs supported. Subscriber server/endpoint has to have trusted certificate to establish https and has to trust any client, so client (hermes-consumers) does not have to have certificate.
