### ISSUE TITLE
Batch delivery

### ISSUE THREAD

**Issue by wojtkiewicz** [allegro/hermes#315]
Subscription should have an option to enable batch delivery. This is especially useful for delivering to Solr or ElasticSearch.

**Comment by adamdubiel** [comment]
Batch sizing: at most N messages, but not rarer than M seconds (if number of messages after M seconds is < N).

**Comment by wendigo** [comment]
Really useful feature in high volume topics :)

**Comment by wojtkiewicz** [comment]
@adamdubiel ...and not more than V mb of data in a batch
