### ISSUE TITLE
Indicate topic versions?

### ISSUE THREAD

**Issue by adamdubiel** [allegro/hermes#326]
When creating new version of topic with uncompatible message schema, we should somehow suggest the naming convention for next versions of topic, e.g.:

```
v1: myTopic-v1
v2: myTopic-v2
```

This might be only a Hermes Console UX modification, while Hermes internals remain unchanged. This is just an idea to consider.

**Comment by druminski** [comment]
Closing it as users already use version in topic name when they need it.
