### ISSUE TITLE
Make handling of not-deliverable messages pluggable

### ISSUE THREAD

**Issue by sslavic** [allegro/hermes#331]
Not deliverable messages get discarded, and strategy how to handle them at the moment doesn't seem to be pluggable. It would be nice if there was Java API using which one could write custom strategy for handling not deliverable messages, package it in JAR and deploy/configure it to hermes-consumer, e.g. to store these messages on S3 or similar, and to skip them (commit in Kafka as processed).

**Comment by adamdubiel** [comment]
That's reasonable - i guess we could do it at low cost.

**Comment by adamdubiel** [comment]
We just got similar request from our internal clients - they would like to see an implementation of such hook that pushes undelivered messages onto sort of dead letter queue on Kafka (created on demand per subscription). I think we will start working on this complex topic in two weeks. Till that time, i think we will just add a way in to plugin own implementations.

**Comment by sslavic** [comment]
Great news, thanks for update!

**Comment by druminski** [comment]
Closing it as probably this feature is not needed any more.
