### ISSUE TITLE
Improve REST API documentation

### ISSUE THREAD

**Issue by sslavic** [allegro/hermes#334]
Consider using RAML or Swagger to document available REST API/endpoints in each of Hermes components - all the different request methods, headers and body schemas supported on the endpoints, as well as all possible response codes, headers and body with meaning, and examples.

**Comment by adamdubiel** [comment]
I am looking towards using Swagger with [SwaggerHub](https://swaggerhub.com/) to document the API, i know this is currenlty a low point. Try using the console though, which is currently available at `develop` branch (and also described in [develop docs](http://hermes-pubsub.readthedocs.org/en/develop/)).

After we solve https issue (there are some small improvements needed to make it work) it should all go in 0.8.4 release.

**Comment by druminski** [comment]
Closing it because we don't want to popularize API of hermes-management as we recommend using hermes-console. In the future we might also introduce Hermes config as a Code which will address additional users use cases.
