### ISSUE TITLE
Upgrade to kafka-clients 0.9.0.1

### ISSUE THREAD

**Issue by sslavic** [allegro/hermes#335]
New async producer, introduced in kafka-clients 0.8.2.x, wasn't stable then and now in new kafka-clients 0.9.0.0 it is much more stable, doesn't lock up / hang indefinitely at least not as often as 0.8.2.x did e.g. when Kafka node goes down, or lead is temporarily unavailable (see https://issues.apache.org/jira/browse/KAFKA-2120 and https://issues.apache.org/jira/browse/KAFKA-1788 ).

**Comment by adamdubiel** [comment]
Currently we don't have 0.9.0 Kafka cluster deployed. I remember we tested those consumers back in -rc days and we had some problems with interoperability with Kafka 0.8.2.2. However we will be migrating surely, we plan on using Kafka 0.9.x when 0.9.0.1 is released with first batch of 0.9.x bugfixes.

**Comment by sslavic** [comment]
We're running Hermes on Kafka 0.9.0.0 cluster, and didn't yet notice issues. Haven't tested/pushed enough yet to see anything. Curious which issues did you experience? Maybe they were fixed in Kafka 0.9.0.0 final release. Also which bugs fixed for Kafka 0.9.0.1 are affecting Hermes?

**Comment by sslavic** [comment]
Btw, by design new consumers (0.9.0.0) do not work with old server (0.8.x)

**Comment by adamdubiel** [comment]
Oh, okay, i knew there was something, yet i didn't code it so didn't remember the exact thing :)

It's not that there are any issues that affect Hermes specifically. Our Kafka-Ops team wants to wait for a 0.9.0.1 before rolling the update on all clusters. Then we will start looking into using new consumers, they will help a lot with resource consumption.

**Comment by sslavic** [comment]
@adamdubiel Kafka 0.9.0.1 has been released http://mail-archives.apache.org/mod_mbox/kafka-users/201602.mbox/%3CCAFc58G9u1ACupurPNMFAERxF59X6EW5CvJphk-vYZR0gdCFFrQ%40mail.gmail.com%3E

**Comment by adamdubiel** [comment]
I know, we already have it packaged and it will arrive on our test this or next week :) Thanks for the notice though!

**Comment by wendigo** [comment]
Can't wait also to see Kafka 0.9.x in our infrastructure :tada:

**Comment by sslavic** [comment]
Please consider testing that Hermes with new consumer client can be easily configured to access Kafka server with security/authentication enabled.

It would give more security options if hermes-consumers was actually migrated to use Kafka 0.10.

Using new Kafka 0.9.x consumer client API in hermes-consumers might be enough for a start, should be less breaking and easier to override Hermes to use Kafka-clients 0.10 if it was on 0.9 already, compared to making existing hermes-consumers to use 0.9+.

**Comment by adamdubiel** [comment]
We will probably make the jump straight to 0.10.x, but afair Consumers protocol is same as in 0.9.0.

**Comment by adamdubiel** [comment]
We skipped right to 0.10, which is done in #558 . Closing this issue.
