### ISSUE TITLE
Add description to configs

### ISSUE THREAD

**Issue by sslavic** [allegro/hermes#336]
Currently config has a name, and default value, but there's no description - especially for hermes specific config properties it's not clear from name only what config property stands for.

Initially description in code only is enough, but ideally it can be used to output configuration information into docs - Kafka project itself does this, config docs generated from source.

**Comment by adamdubiel** [comment]
We tried to document everything in docs - they include description as well. I don't know about adding documentation in code as well, if it will be descriptive enough (for example documenting consumers algorithm).

**Comment by sslavic** [comment]
I'm referring to https://github.com/allegro/hermes/blob/master/hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java

**Comment by adamdubiel** [comment]
I know, and you have all those options documented in sections of documentation like:
http://hermes-pubsub.readthedocs.org/en/latest/configuration/frontend-tuning/ or http://hermes-pubsub.readthedocs.org/en/latest/configuration/rate-limiting/ . Of course we can add some descriptions in Config.java, although i'm afraid it will soon be out of sync.
