### ISSUE TITLE
Missing events on consumer crash for new subscription

### ISSUE THREAD

**Issue by chemicL** [allegro/hermes#351]
It might happen that we miss events that fail to be delivered to the subscription endpoint in a specific scenario.

Steps to reproduce:
1. Launch a consumer.
2. Create subscription to a failing endpoint (e.g. endpoint unreachable.)
3. Send N messages to the topic.
4. Stop consumer.
5. Launch endpoint.
6. Start consumer.
7. Observe nothing gets delivered.

Upon sending message N+1, this message and subsequent get delivered.

Why is this a problem?
- Say we have 1 message which causes the server to reply with status 500 and we keep retrying to deliver the message before it's TTL expires.
- After that we deliver N successful messages and then stop the consumer.
- The offsets were not committed and we would normally have re-delivered the messages in normal case.
- However, when this is a fresh subscription, an offset has not yet been committed for it, therefore the message is lost without us acknowledging it.

**Comment by adamdubiel** [comment]
I think this is because the subscription was never created until there is at least one committed message. I don't know if this is a major problem.

**Comment by druminski** [comment]
Closing this issue as it’s ok behaviour.
