### ISSUE TITLE
Support basic authentication of Hermes to subscribers

### ISSUE THREAD

**Issue by sslavic** [allegro/hermes#360]
Access to subscriber endpoints can be protected. Subscriber should be able to allow only Hermes to make requests to subscription endpoints. HTTP basic authentication is one popular way how access to subscriber endpoint can be protected. Please build appropriate support in Hermes.

For a start it would be enough to allow subscribers to specify whether they want to use basic authentication or not in their subscription, and, if they do, which credentials should Hermes use when sending/pushing messages. Credentials should be stored in encrypted form.

**Comment by adamdubiel** [comment]
Same answer as #359 applies here as well (although implementation is a lot easier).

**Comment by miguelpuyol** [comment]
We are trying to configure a subscription with a subscriber with Basic Auth enabled. We saw in your pl.allegro.tech.hermes.api.EndpointAddress that you are masking the password when an endpoint is set like: http://user:password@myurl.com.

@adamdubiel mentioned on Gitter that this is used for JMS consumers and that it would be easy to implement it  for the http sender as well

**Comment by adamdubiel** [comment]
First iteration of adding Basic Auth: https://github.com/allegro/hermes/pull/419

There is no secure storage though, as that is a broader matter. Let me know if that solves any of your problems.

**Comment by adamdubiel** [comment]
This pull request was merged and is scheduled to be released in 0.8.7. Let me know if you want to deploy snapshot somewhere first - i can release `0.8.7-develop-SNAPSHOT`.

**Comment by adamdubiel** [comment]
Stale issue, closing :)
