### ISSUE TITLE
Support protecting access to Hermes endpoints

### ISSUE THREAD

**Issue by sslavic** [allegro/hermes#362]
Would be nice to be able to protect access to Hermes endpoints using:
- basic authentication
- HTTPS client authentication

**Comment by adamdubiel** [comment]
Which module do you have in mind? Frontend/Management?

**Comment by sslavic** [comment]
Both :)

**Comment by adamdubiel** [comment]
Okay :) Management is already ["securable"[(http://hermes-pubsub.readthedocs.org/en/latest/configuration/security/) and we have some policies implemented internally (OAuth+JWT tokens), which i think should get opensourced in near future. As to the Frontend - it's a similar issue to Consumers.

**Comment by miguelpuyol** [comment]
Hey @adamdubiel we tested the the Basic Auth solution and works for us!

Thanks again

**Comment by adamdubiel** [comment]
Consumer now supports both OAuth and Basic Auth (since 0.8.11) - i think i should close this issue. Frontend is another beast :)
