### ISSUE TITLE
Broadcast mode in subscription

### ISSUE THREAD

**Issue by adamdubiel** [allegro/hermes#372]
Allow `EndpointResolver` to return multiple endpoints. If subscription has **broadcast** mode on, the messages will be broadcasted to all resolved addresses. Otherwise only 1st address is used.

We need to figure out retransmissions, either:

* no retransmissions (probably easier)
* retransmit until all instances ack

**Comment by rafal-glowinski** [comment]
Yes yes! Pretty please :) I vote for 2nd one.

**Comment by adamdubiel** [comment]
This change will involve changes in [SerialConsumer](https://github.com/allegro/hermes/blob/d7dba18c3e5f21a07cdff493d278e376f5ece4fe/hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/SerialConsumer.java) and [EndpointAddressResolver](https://github.com/allegro/hermes/blob/28ec77ad48e05dd9f75662d74f1f9630ec11b253/hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/resolver/EndpointAddressResolver.java).

The easy part is making `EndpointAddressResolver` return list of addresses instead of just one (although remember to keep the backwards compatibility of this interface, probably some default method will be helpful). The hard part is making one-to-many relationship work in sender and retries. Message can't be committed unless it has been ackd by all consuming nodes.
