### ISSUE TITLE
Issue with Hermes Frontend  as standalone  jar

### ISSUE THREAD

**Issue by hikrrish** [allegro/hermes#391]

**Comment by hikrrish** [comment]
A MultiException has 41 exceptions.  They are:
1. java.lang.RuntimeException: java.lang.AbstractMethodError: org.jvnet.hk2.internal.DynamicConfigurationImpl.addIdempotentFilter([Lorg/glassfish/hk2/api/Filter;)V
2. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of pl.allegro.tech.hermes.infrastructure.schema.CachedSchemaSourceProviderFactory errors were found
3. java.lang.IllegalStateException: Unable to perform operation: resolve on pl.allegro.tech.hermes.infrastructure.schema.CachedSchemaSourceProviderFactory
4. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of pl.allegro.tech.hermes.infrastructure.schema.AvroSchemaRepositoryFactory errors were found
5. java.lang.IllegalStateException: Unable to perform operation: resolve on pl.allegro.tech.hermes.infrastructure.schema.AvroSchemaRepositoryFactory
6. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of pl.allegro.tech.hermes.frontend.validator.AvroTopicMessageValidator errors were found
7. java.lang.IllegalStateException: Unable to perform operation: resolve on pl.allegro.tech.hermes.frontend.validator.AvroTopicMessageValidator
8. java.lang.RuntimeException: java.lang.AbstractMethodError: org.jvnet.hk2.internal.DynamicConfigurationImpl.addIdempotentFilter([Lorg/glassfish/hk2/api/Filter;)V
9. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of pl.allegro.tech.hermes.infrastructure.schema.CachedSchemaSourceProviderFactory errors were found
10. java.lang.IllegalStateException: Unable to perform operation: resolve on pl.allegro.tech.hermes.infrastructure.schema.CachedSchemaSourceProviderFactory
11. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of pl.allegro.tech.hermes.infrastructure.schema.JsonSchemaRepositoryFactory errors were found
12. java.lang.IllegalStateException: Unable to perform operation: resolve on pl.allegro.tech.hermes.infrastructure.schema.JsonSchemaRepositoryFactory
13. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of pl.allegro.tech.hermes.frontend.validator.JsonTopicMessageValidator errors were found
14. java.lang.IllegalStateException: Unable to perform operation: resolve on pl.allegro.tech.hermes.frontend.validator.JsonTopicMessageValidator
15. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of pl.allegro.tech.hermes.frontend.validator.TopicMessageValidatorListFactory errors were found
16. java.lang.IllegalStateException: Unable to perform operation: resolve on pl.allegro.tech.hermes.frontend.validator.TopicMessageValidatorListFactory
17. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of pl.allegro.tech.hermes.frontend.validator.MessageValidators errors were found
18. java.lang.IllegalStateException: Unable to perform operation: resolve on pl.allegro.tech.hermes.frontend.validator.MessageValidators
19. java.lang.RuntimeException: java.lang.AbstractMethodError: org.jvnet.hk2.internal.DynamicConfigurationImpl.addIdempotentFilter([Lorg/glassfish/hk2/api/Filter;)V
20. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of pl.allegro.tech.hermes.infrastructure.schema.CachedSchemaSourceProviderFactory errors were found
21. java.lang.IllegalStateException: Unable to perform operation: resolve on pl.allegro.tech.hermes.infrastructure.schema.CachedSchemaSourceProviderFactory
22. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of pl.allegro.tech.hermes.infrastructure.schema.AvroSchemaRepositoryFactory errors were found
23. java.lang.IllegalStateException: Unable to perform operation: resolve on pl.allegro.tech.hermes.infrastructure.schema.AvroSchemaRepositoryFactory
24. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of pl.allegro.tech.hermes.frontend.publishing.MessageContentTypeEnforcer errors were found
25. java.lang.IllegalStateException: Unable to perform operation: resolve on pl.allegro.tech.hermes.frontend.publishing.MessageContentTypeEnforcer
26. java.lang.RuntimeException: java.lang.AbstractMethodError: org.jvnet.hk2.internal.DynamicConfigurationImpl.addIdempotentFilter([Lorg/glassfish/hk2/api/Filter;)V
27. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of pl.allegro.tech.hermes.infrastructure.schema.CachedSchemaSourceProviderFactory errors were found
28. java.lang.IllegalStateException: Unable to perform operation: resolve on pl.allegro.tech.hermes.infrastructure.schema.CachedSchemaSourceProviderFactory
29. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of pl.allegro.tech.hermes.infrastructure.schema.AvroSchemaRepositoryFactory errors were found
30. java.lang.IllegalStateException: Unable to perform operation: resolve on pl.allegro.tech.hermes.infrastructure.schema.AvroSchemaRepositoryFactory
31. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of pl.allegro.tech.hermes.common.message.wrapper.MessageContentWrapper errors were found
32. java.lang.IllegalStateException: Unable to perform operation: resolve on pl.allegro.tech.hermes.common.message.wrapper.MessageContentWrapper
33. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of pl.allegro.tech.hermes.frontend.publishing.metadata.MetadataAddingMessageConverter errors were found
34. java.lang.IllegalStateException: Unable to perform operation: resolve on pl.allegro.tech.hermes.frontend.publishing.metadata.MetadataAddingMessageConverter
35. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of pl.allegro.tech.hermes.frontend.publishing.PublishingServlet errors were found
36. java.lang.IllegalStateException: Unable to perform operation: resolve on pl.allegro.tech.hermes.frontend.publishing.PublishingServlet
37. java.lang.RuntimeException: java.lang.AbstractMethodError: org.jvnet.hk2.internal.DynamicConfigurationImpl.addIdempotentFilter([Lorg/glassfish/hk2/api/Filter;)V
38. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of pl.allegro.tech.hermes.infrastructure.schema.CachedSchemaSourceProviderFactory errors were found
39. java.lang.IllegalStateException: Unable to perform operation: resolve on pl.allegro.tech.hermes.infrastructure.schema.CachedSchemaSourceProviderFactory
40. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of pl.allegro.tech.hermes.frontend.server.HermesServer errors were found
41. java.lang.IllegalStateException: Unable to perform operation: resolve on pl.allegro.tech.hermes.frontend.server.HermesServer

**Comment by hikrrish** [comment]
Above is the multi exception I am getting 

running as standalone with config.properties file. Please suggest me the configuration for standalone run of hermes modules

**Comment by hikrrish** [comment]
Above issue is solved by adding 
		<dependency>
			<groupId>org.glassfish.hk2</groupId>
			<artifactId>hk2</artifactId>
			<version>2.5.0-b03</version>
		</dependency>

**Comment by adamdubiel** [comment]
Thanks for the tip, we will take a look at why it happened.

**Comment by craigmcc** [comment]
Our dependencies policies don't allow for import of beta or snapshot releases, but that exception goes away if you explicity request version 2.4.0 as well.

**Comment by druminski** [comment]
Hermes doesn’t have standalone jars. We are using distZip task which provides zip. You can run by ```
./gradlew distZip -Pdistribution
```
