### ISSUE TITLE
Incorrect multi-threaded code for handling message publishing

### ISSUE THREAD

**Issue by konrad-kaminski** [allegro/hermes#397]
In `PublishingServlet` a `MessageReader` object is constructed and not used any more. The whole logic of providing the `MessageReader` to servlet input stream (as a `ReadListener`) is done inside `MessageReader` constructor. This may behave badly as a not-fully constructed object can be potentially used in a different thread. 

Additionally the initial state for timing metrics should be set _before_ a call to `inputStream.setReadListener()` so that they are visible to the thread which uses the provided `ReadListener`.

**Comment by adamdubiel** [comment]
The code went through some major refactors, `PublishingServlet` does not exist anymore (not saying there are no bugs, just not exactly this one).
