### ISSUE TITLE
Hermes Console should exclude 503 + Retry After responses from 5xx problems reporting

### ISSUE THREAD

**Issue by rafal-glowinski** [allegro/hermes#412]
Currently, when Hermes Console presents subscription status/health it also displays additional textual description, for example: "Consuming service returns a lot of 5xx codes. Looks like it might be malfuncioning or doesn't know how to handle messages. Take a look at "Last undelivered message" for more information."

I think that since Hermes now supports Retry After header in response from Subscriber, and such 503 replies don't influence the pace at which messages are being sent to Subscriber then it should not be reported as a problem with Subscription.

**Comment by druminski** [comment]
Closing is as RetryAfter header is not a popular feature and Hermes have better retry policy now.

**Comment by rafal-glowinski** [comment]
:(

W dniu czw., 22.04.2021 o 10:57 Łukasz Drumiński ***@***.***>
napisał(a):
