### ISSUE TITLE
Slow consumer

### ISSUE THREAD

**Issue by gamefundas** [allegro/hermes#424]
I managed to get everything running & working on AWS but noticed that the Hermes consumer is processing the messages very slow. My consumer on the Kafka side for the same subscription is quick to pick the messages and processing in real time. 

While Hermes appears to be processing in batches of 30 sec and the endpoint is receiving the message with several minutes of delay. Do I need to do something on the consumer configuration end to make this work in real time.

The configurations of all components so far are pretty much defaults.

**Comment by adamdubiel** [comment]
Can you rule out any timeouts etc that would cause Consumer to retry the message multiple times until it is accepted by server? How much traffic are you sending? You are the 2nd (first being @kkorbacz) that reports this kind of issue, which we never observed on any of our clusters. When creating new subscription, we get the data straight away.

**Comment by gamefundas** [comment]
Ok figured out my nodejs server Http response wasn't 200. This was blocking the Hermes consumer I guess. After fixing my client for the first few minutes the messages were slow then it recovered by itself. Not sure if any connections remained open and it was preventing the new messages to go through.

If you cant think of anything else we can close this issue for now.

**Comment by adamdubiel** [comment]
Hermes accepts any 2xx statuses as "OK". The "first few minutes" slow responses after fixing the server is actually how the backpressure algorithm works :) After seeing that your service is ok to accept the requests, Hermes started to gradually increase sending speed, seeing if the service is still able to manage it.

If you want to know more about rate limiting algorithm, you can read the details:

* http://hermes-pubsub.readthedocs.org/en/latest/user/subscribing/#rate-limiting
* http://hermes-pubsub.readthedocs.org/en/latest/configuration/rate-limiting/

**Comment by adamdubiel** [comment]
By the way, you could observe response statuses, response times, current sending rate and much more if you configured Hermes to send data to Graphite. We have tons of metrics there, very helpful when trying to reason what is actually happening :)

http://hermes-pubsub.readthedocs.org/en/latest/deployment/metrics/
http://hermes-pubsub.readthedocs.org/en/latest/configuration/metrics/

**Comment by gamefundas** [comment]
Thanks Adam for the explanation. This helps.

As for metrics, is there a plan to use Elasticsearch in the future. Graphite is kind of hard to setup and I have seen many projects move to ES with Kibana and Grafana serving monitoring dashboards.

You already have trace information going in to ES, you could have a common backend for both. Just a thought.

**Comment by adamdubiel** [comment]
Actually you can plug anything as long as it's a Dropiwzard Metrics reporter. If you need help with that i will be happy to guide you. Currently at Allegro we use Graphite, but are actively looking for a better alternative (it's a real pain with serious traffic) and probably other implementations will show up.
