### ISSUE TITLE
Use Kafka to communicate changes from Management to Frontend and Consumers

### ISSUE THREAD

**Issue by adamdubiel** [allegro/hermes#428]
Currently we rely in great deal on Zookeeper watches to communicate changes/updates in Hermes Management. Since we actually have a pretty decent (;)) pubsub between Hermes modules, it could be used to communicate changes. Zookeeper watches start to malfunction at scale of 600 subscriptions, some of them updated frequently (our test env).

This is a nice-to-have, since we are not hitting the wall just yet.

**Comment by druminski** [comment]
After three years of working on production we don’t have problems with described problem. Recently we have provided refeactoring which decreased watches number.
