### ISSUE TITLE
Pass Http headers to consumer endpoints

### ISSUE THREAD

**Issue by gamefundas** [allegro/hermes#429]
Is there any way we could pass Http headers like content-type, accept etc through front-end and that can be carried over/set to the consumer endpoints? This would help in case of streaming non-avro payloads to Spring MVC REST endpoints.

Hermes could probably use the Metadata region to piggyback this information.

**Comment by adamdubiel** [comment]
Yes, there is a way. I once promised to make it configurable via configuration, not via API. Via API you can do it by registering custom [HeadersPropagator](https://github.com/allegro/hermes/blob/3c5834a792dc2455535016f23451ae95c7643596/hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/metadata/HeadersPropagator.java) in Hermes Frontend, which extracts headers from request and puts them into metadata:

```
builder.withHeadersPropagator(new CustomHeaderPropagator());
```

Default implementation of Consumers Jetty sender appends all headers to outgoing request without any configuration needed.

**Comment by gamefundas** [comment]
This worked. We should be able to close the issue.
