### ISSUE TITLE
ques : Management module service discovery integration

### ISSUE THREAD

**Issue by hikrrish** [allegro/hermes#440]
Hi,

I have a question on hermes management module, we are using discovery service for all internal communication and we are wondering as part of startup hook we can plugin our code for creation and subscription of groups and topics using service discovery. do we have such feature available with management ? 

Thanks

**Comment by gamefundas** [comment]
Given that Management is a Spring boot module we can package a Configuration (ServiceDiscoveryConsulConfiguration) ourselves to make the management endpoint discoverable. 

Adam, this will help in cases where the application will be configured to own subscriptions at the time of startup.

**Comment by adamdubiel** [comment]
It's like @gamefundas said, just add own configuration, at least this is what we do - adding own Spring Boot config which registers Management in Consul.
