### ISSUE TITLE
Offsets are commited to wrong place in batch consumers.

### ISSUE THREAD

**Issue by druminski** [allegro/hermes#446]
BatchConsumer loses information about kafka topic name and commits offsets to invalid topic/path. When batch consumer restart occurs then messages will be probably read again from the topic beginning.

Info about kafka topic name is kept in PartitionOffset class which is lost in batch consumer here:
https://github.com/allegro/hermes/blob/240090990ce12ef218257149673fb100a51097f4/hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/batch/MessageBatchReceiver.java#L108

**Comment by adamdubiel** [comment]
Closed by https://github.com/allegro/hermes/pull/452
