### ISSUE TITLE
Underscore in topic name leads to invalid nodes creation in zk.

### ISSUE THREAD

**Issue by druminski** [allegro/hermes#448]
When topic is created via Hermes API and it contains underscore in the name, for example `topic_v1` then node with the same name is created in zk. However when messages are published on that topic then counters are reported in zk under `topic.v1/metrics/published` node. The problem is that when metrics are reported to zk, then underscore is converted to dot and new empty topic node is created. This leads to invalid structures creation in zk and prevents me from listing all subscriptions via /query/subscriptions endpoint because `Unable to read data from path` is thrown.

**Comment by adamdubiel** [comment]
Fixed by #741
