### ISSUE TITLE
How to set  external id for message tracking 

### ISSUE THREAD

**Issue by hikrrish** [allegro/hermes#457]
I see below message in my elastic search tracking, however I could not make out any information as there is not external id to this message. I can see batch id here which is empty Can  we set batch id to some external id  for tracking. 

{
"_index": "sent_messages_2016_04_22",
"_type": "sent_message",
"_id": "AVQ7rNDgFdi6dYiXdos6",
"_version": 1,
"_score": 1,
"_source": {
"messageId": "2125d4e6-fd68-49a8-b813-02723ad362e0",
"batchId": "",
"timestamp": 1461290060244,
"publish_timestamp": 1461290060196,
"topicName": abc.bbc",
"subscription": "mySubscription_test_2",
"status": "INFLIGHT",
"offset": 0,
"partition": 5,
"cluster": "primary"
},
"sort": [
1
]
}

**Comment by adamdubiel** [comment]
The `batch id` field is reserved for batch uses, an incubating feature. The `message id` field contains `Hermes-Message-Id`, which is generated by Hermes and is returned to client in `Hermes-Message-Id` response header. If publisher logs this Id, it can be used to track messages. You don't need any external id in this case :)

http://hermes-pubsub.readthedocs.org/en/latest/user/publishing/#message-id

**Comment by hikrrish** [comment]
I think batch id  would be useful for us as it will have some business context . Yeah,  we will be using Hermes-Message-Id for now. 

Thanks
