### ISSUE TITLE
Upgrade Hermes-Client to use OkHttp3

### ISSUE THREAD

**Issue by rafal-glowinski** [allegro/hermes#477]
Currently Hermes-Client uses old version of OkHttp. I think it is time to move to much newer version.

**Comment by rafal-glowinski** [comment]
It turns out that OkHttp3 no longer sets a header with used protocol version. I have discussed it with Adam, and we have agreed to add new method to HermesResponse: String getProtocol() that would by default return "http/1.1" for all the clients (which don't support HTTP/2 yet) and would be set accordingly for OkHttpSender.

**Comment by adamdubiel** [comment]
Closing the issue - merged.

**Comment by adamdubiel** [comment]
Thanks for the contribution :)
