### ISSUE TITLE
Support trusting all certificates of https subscribers

### ISSUE THREAD

**Issue by sslavic** [allegro/hermes#504]
Mainly for testing purposes (self-signed https subscribers), please consider adding support in hermes-consumers for trusting all certificates of https subscribers.

One possible solution would be that a feature flag gets added, e.g. "consumer.http.client.trust.all.certificates", which would be false by default and used in HttpClientFactory.sslContextFactory to construct and configure appropriate SslContextFactory instance.

**Comment by adamdubiel** [comment]
I think it gets fixed with #666 and addition of `consumer.http.client.validate.certs` option (default to `true`).
