### ISSUE TITLE
Subscription metadata

### ISSUE THREAD

**Issue by dankraw** [allegro/hermes#514]
Subscriptions model should allow for storing additional metadata.

**Comment by wojtkiewicz** [comment]
How about making subscription more dynamic and allow for storing arbitrary key/value?

Example:
```
public boolean getProperty(String key, T default) {
    return configuration.getOrDefault(key, default);
}

public boolean isTrackingEnabled() {
    return configuration.getOrDefault("trackingEnabled", false);
}
```

**Comment by dankraw** [comment]
@wojtkiewicz I would vote for something similar to this as a feature of the upcoming 1.0.0, we should make the Subscription/Topic model somehow extendable.

**Comment by wojtkiewicz** [comment]
@dankraw extensions would consume properties like this for instance:
```
class FoobarEndpointAddressResolver implements EndpointAddressResolver {
    URI resolve(EndpointAddress address, Subscription sub) {
       return sub.getProperty(Extensions.FOOBAR_ENABLED, false)? foobar() : resolve(address);
    }
}
```

**Comment by adamdubiel** [comment]
This looks like "Context" bag. If i need to have "Context" bag, i would like to limit the occurence to minimal - i.e. in some named properties like `resloverMetadata`, `authMetadata` etc.

**Comment by wojtkiewicz** [comment]
I think that adding new bags for each new context does not scale very well and class gets populated with "bags" that are not actually used anywhere inside source code. You can narrow down context if you want by introducing allowed namespaces or something similar.

**Comment by adamdubiel** [comment]
Your example shows putting a lot of stuff which is now basically hermes features (i.e. tracking) inside "context bags". I think this pollutes domain and will be a major pain in the future. Although it forces us to throw Subscription everywhere instead of building more cohesive interfaces.

**Comment by wojtkiewicz** [comment]
This is something that is extensible and it does not require extensions to hack subscription model (neither inheritance nor custom subscription is required). Alternative with metadata objects that store arbitrary values makes interfaces with maps in them as an argument (if extensions won't have an access to subscription object).

**Comment by wojtkiewicz** [comment]
What I'm trying to say is that if we allow to introduce custom subscription configuration then it should be a first class citizen. Otherwise its just a hack.

**Comment by adamdubiel** [comment]
Yeah, i'm trying to do the same. But i want to limit the scope so that we know whats inside the bags and we can pass smaller objects around.
