### ISSUE TITLE
Receiving Payload/ ACK from clients in consumer module 

### ISSUE THREAD

**Issue by hikrrish** [allegro/hermes#522]
@adamdubiel 
Is there a way for consumer module to get the ACK reposne plus the payload as well when the message is successfully consumed by the client ? if not,   Could you please add this in 1.0 Road Map

Also please provision a external id (apart from hermes message id) to batch the messages.

**Comment by adamdubiel** [comment]
I think i need some more details, real examples/cases would be the best :)

1) What do you mean by ACK + payload? What would this payload be and how would it be used? Should consumer save it somewhere?
2) What kind of external-id? You can send the ID either inside the message or as a custom header, which is later transported to subscriber. Also since 0.8.7 we have batching support built in - is this what you are looking for?

**Comment by hikrrish** [comment]
1) We are building services in which clients do send us ACK or some unique ID once they receive a message, also http response payload. I am trying to plugin code in message sender providers  to print / persist the ack or any response from clients at the point when consumer publishes the message.

2) I am fine with this now 

Thanks

**Comment by adamdubiel** [comment]
I wonder if it is necessary - how does it differ from having a [tracking](http://hermes-pubsub.readthedocs.io/en/latest/user/subscribing/#message-tracking) enabled on subscription? You persist state of each message, also the response code from subscriber. So you can see each individual message and whether it was acked/received or not.

**Comment by hikrrish** [comment]
yes you are right, we are already using message tracking. However, in my use case,  client is sending back a response payload and we need to plug in our response message handling for the payload in consumer module. we are already using custom message sender provider (http sender). i wonder if I can plugin the response message handler in consumer to handle this use case..


Thanks

**Comment by adamdubiel** [comment]
Okay, there is no straightforward support for this kind of thing. If you want to do it, you would probably need to introduce new component somewhere in [DefaultSuccessHandler](https://github.com/allegro/hermes/blob/28ec77ad48e05dd9f75662d74f1f9630ec11b253/hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/result/DefaultSuccessHandler.java).

**Comment by druminski** [comment]
Closing it as this issue was open for 5 years and not realized, assuming it's not very important.
