### ISSUE TITLE
Upgrade gradle wrapper to 2.14

### ISSUE THREAD

**Issue by sslavic** [allegro/hermes#527]
Please consider upgrading gradle wrapper to 2.14. Please also reference Gradle distribution with sources, like https\://services.gradle.org/distributions/gradle-2.14-all.zip in hermes/gradle/wrapper/gradle-wrapper.properties

**Comment by adamdubiel** [comment]
We surely will update to newest one, but we won't use `-all` distribution in wrapper settings. This is an unnecessary strain on CI servers, we don't need Gradle sources to build Hermes.

**Comment by adamdubiel** [comment]
Fixed in #505
