### ISSUE TITLE
SelectiveSupervisorControllersIntegrationTest.shouldElectNewLeaderAfterShutdown unstable

### ISSUE THREAD

**Issue by sslavic** [allegro/hermes#531]
SelectiveSupervisorControllersIntegrationTest.shouldElectNewLeaderAfterShutdown test seems to be unstable, oscillates, fails randomly from build to build.

**Comment by adamdubiel** [comment]
I fixed this tests in https://github.com/allegro/hermes/pull/548 - hopefully it will perform better.
