### ISSUE TITLE
Cleanup unused imports from ConsumerFactory

### ISSUE THREAD

**Issue by sslavic** [allegro/hermes#532]
All the imports starting from https://github.com/allegro/hermes/blob/master/hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/ConsumerFactory.java#L22 seem to be unused. Please consider removing them.

**Comment by adamdubiel** [comment]
This will be fixed with #505 , so i'm closing the issue. Of course there are some other unused imports in the whole project, but we are integrating with @sputnikci for findbugs & pmd integration in review comments to clean up the codebase step by step (and keep it clean afterwards).
