### ISSUE TITLE
Make filtering Subscription aware

### ISSUE THREAD

**Issue by sslavic** [allegro/hermes#536]
One use case where this would be useful - SubscriptionMessageFilterCompiler could pass on subscription information to Predicate<Message>, and that subscription information could be used during filtering/testing e.g. to use subscription name to provide context for filter debug logging messages.

**Comment by adamdubiel** [comment]
Any specific fields (except SubscriptionName) you would like to see? We would like to contain the information and pass only the important bits.

**Comment by sslavic** [comment]
Even better, make FilterChain aware of Subscription it belongs to, and pass that information to filter, so both subscription specific and global filters can use it as context during filtering.

**Comment by sslavic** [comment]
One can validate on management side as well that all subscriptions have necessary metadata for given global filter, but consumers needs to protect itself from invalid data as well.

For a global filter to check/enforce specific MessageFilterSpecification is set in every subscription, besides Subscription's name, filter would need access to Subscription's filters collection, or at least optional of MessageFilterSpecification for that filter.

So simplest would be that "FilterContext" has both Message and Subscriptions, and that FilterContext gets passed along by FilterChain to Filter(s) instead of just a Message.

**Comment by sslavic** [comment]
Ended up adding Subscription to both MessageFilterSpecification and FilterChain/FilterContext, to make both filter compile time, and filtering - Subscription aware.

**Comment by adamdubiel** [comment]
Based on this quote:

> filter would need access to Subscription's filters collection

It looks like you are trying to get around the problem. Allowing filter to reach into the subscription filters is an example of behaviour we would not want to see - now anything in subscription becomes part of public Filter API.

As far as i remember it is possible to define global filter which will be used always, regardless of what filters subscription defined, but @wojtkiewicz will correct me if i'm wrong.

**Comment by sslavic** [comment]
Solved it for now by duplicating subscription name in filter specification, to make it accessible to filter compiler and predicate.
