### ISSUE TITLE
KafkaConsumer 0.10

### ISSUE THREAD

**Issue by wojtkiewicz** [allegro/hermes#558]
*Adoption of:*
https://kafka.apache.org/0100/javadoc/index.html?org/apache/kafka/clients/consumer/KafkaConsumer.html

*Implementation proposal:*
- one KafkaConsumer per Hermes Consumer thread
- number of established tcp connections wouldn't change
- number of threads would go down because we no longer maintain separate thread pool dedicated to zookeeper/kafka message streaming, instead actual Consumer threads would both fetch and process message from kafka

*Implementation limitation:*
- number of tcp connections remains relatively high: for every Consumer we would establish connection with every broker in a cluster which gives us roughly *n* times *m* connections per host where *n* is number of subscriptions per host and *m* is number of brokers in a cluster

*Scalability:*
At the moment we have 500 subscriptions per host, 3 consumer nodes, 4 broker nodes. This approach theoretically should scale at least to 1000 subscriptions per host, 50 consumer nodes, 20 broker nodes. Above those figures number of open files gets close to 65k on both consumer node and broker node. Technically upper limit for open tcp connections should be around 300k for kafka broker but we don't know how much stress that would cause to entire cluster.

*Alternative implementation:*
In the long term we could develop our own tcp connection management so we can keep number of connections to brokers constant per host regardless of subscriptions and broker count. With that being said cost of development and maintenance is relatively high because we cannot reuse KafkaConsumer, only internal components that may or may not change in upcoming releases.

**Comment by wojtkiewicz** [comment]
*Adoption of:*
https://kafka.apache.org/0100/javadoc/index.html?org/apache/kafka/clients/consumer/KafkaConsumer.html

*Implementation proposal:*
- one KafkaConsumer per Hermes Consumer thread
- number of established tcp connections wouldn't change
- number of threads would go down because we no longer maintain separate thread pool dedicated to zookeeper/kafka message streaming, instead actual Consumer threads would both fetch and process message from kafka

*Implementation limitation:*
- number of tcp connections remains relatively high: for every Consumer we would establish connection with every broker in a cluster which gives us roughly *c = n*m* connections per host where *n* is number of subscriptions per host and *m* is number of brokers in a cluster

*Scalability:*
At the moment we have 500 subscriptions per host, 3 consumer nodes, 4 broker nodes. This approach theoretically should scale at least to 1000 subscriptions per host, 50 consumer nodes, 20 broker nodes. Above those figures number of open files gets close to 65k on both consumer node and broker node. Technically upper limit for open tcp connections should be around 300k for kafka broker but we don't know how much stress that would cause to entire cluster.

*Alternative implementation:*
In the long term we could develop our own tcp connection management so we can keep number of connections to brokers constant per host regardless of subscriptions and broker count. With that being said cost of development and maintenance is relatively high because we cannot reuse KafkaConsumer, only internal components that may or may not change in upcoming releases.

**Comment by sslavic** [comment]
If I may add, one outcome that I would expect from this is that it's possible to enable and use ZooKeeper and Kafka security features without Hermes imposed limitations (e.g. authentication and authorization plaintext and Kerberos, TLS).

Besides using new Kafka Consumer APIs that would require additional work, e.g. that Hermes's KafkaBrokerTopicManagement and KafkaConfiguration get refactored not use ZkClient directly but through ZkUtils Kafka's abstraction, and to make isZkSecurityEnabled parameter of ZkUtils configurable.

**Comment by adamdubiel** [comment]
This is a non-goal in this specific issue/pull request. What we want to achieve now is using new Kafka protocol in place of the old one. Of course what you point out is a valid request, but this PR/issue can be completed without it. Mostly because switching to new version of protocol is a big task by itself and i would not want to add any additional things that might blur our focus.

Also since we won't be using any Kafka security features in foreseeable future, it would be best if you could provide a tested pull request, since it is hard to develop a production-ready feature without actually running it on prod :)

**Comment by sslavic** [comment]
It wasn't possible to migrate to new consumer API without migrating rest of the new Kafka APIs, and this is already done in the existing PR.

Haven't reviewed everything yet in the PR, but made one small remark (see [here](https://github.com/allegro/hermes/pull/569/files#r77968844)), related to my previous request, if possible not to artificially impose limitations on new security features. I hope you agree it's small enough change request to be made in this issue/PR.

We will review more and test with security enabled, and report issues accordingly if not PRs as well.

Thanks for all the hard work done already on upgrading to new consumer API!

**Comment by adamdubiel** [comment]
This will be release in 0.9.0 today - we have been running it on prod for ~1 week and the results are very good - less threads, smaller mem & cpu consumption and increased overall stability.

The only issue is that moving to Kafka 0.10 is all or nothing process - you need to stop all consumers and start them in new version, since ZK consumers groups are not the same as Kafka consumer groups.
