### ISSUE TITLE
HermesShutdownHandler never finishes unless killed

### ISSUE THREAD

**Issue by chemicL** [allegro/hermes#562]
Sometimes frontend doesn't shutdown properly and gets stuck on

```
p.a.t.h.f.s.HermesShutdownHandler - Buffer flush: 16384 bytes still in use
```

The first issue is using metrics to get the buffer used bytes instead of the buffer itself.
The next is ensuring that a timeout is provided. Next launch of frontend should deal with the buffer.

**Comment by adamdubiel** [comment]
Closed with #503
