### ISSUE TITLE
Gracefully handle missing groups ZooKeeper node when listing existing group names

### ISSUE THREAD

**Issue by sslavic** [allegro/hermes#568]
It seems Hermes consumers depends on Hermes management being started first, correct?
Hermes management initializes at least some ZooKeeper nodes without which Hermes consumers can fail starting e.g. /hermes/groups node.

When NotificationsBasedSubscriptionCache starts, it tries to list group names via ZookeeperGroupRepository and that fails with ZKs NoNodeException if groups node is not there

Maybe pathExists (for groups node) check could be done before https://github.com/allegro/hermes/blob/da212447f3e8d939c36a87fcaa71ac79caa32ed9/hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperGroupRepository.java#L90 and only if it exists then ask for children of /groups, otherwise return empty list of names

Maybe hermes consumers could ensure itself required ZK nodes are present during initialization/startup, would make it more resilient to these conditions

ZookeeperGroupRepositoryTest doesn't seem to test how listGroupNames is supposed to behave when /hermes/groups does not exist.

Please have these problems fixed.

**Comment by druminski** [comment]
Closing it as this is probably not a problem anymore. As far as I remember you can start consumers module before management and it's ok now.
