### ISSUE TITLE
Missing consumers in selective algorithm

### ISSUE THREAD

**Issue by druminski** [allegro/hermes#574]
Consumers don't comeback to selective algorithm after they lose connection to zookeeper.

For example in this zookeeper should be three consumers instances but was only one:

<img width="1023" alt="screen shot 2016-09-13 at 20 40 09" src="https://cloud.githubusercontent.com/assets/4473056/18506869/2ea7075c-7a6e-11e6-8f7c-047825c9518a.png">

**Comment by adamdubiel** [comment]
Fixed in 0.9.0 with new Kafka API.
