### ISSUE TITLE
Can't create a topic if the name contains a `.` (dot) character

### ISSUE THREAD

**Issue by ghost** [allegro/hermes#575]
When trying to create a new topic that it's name contains a dot character e.g (topic.name), with the following request body.

``` javascript
{
    "name": "test.topicowner.topic.name",
    "description": "description",
    "contentType": "JSON",
    "ack": "LEADER",
    "retentionTime": {
        "duration": 500
    }
}
```

I receive the following `404` error.

``` javascript
{
  "message": "Group test.topicowner.topic does not exist",
  "code": "GROUP_NOT_EXISTS"
}
```

Although the group name I've created is `test.topicowner`. Still can find on code that the validation allows a dot character !.

``` java
public final class Names {
    public static final String ALLOWED_NAME_REGEX = "[a-zA-Z0-9_.-]+";
}
```

**Comment by adamdubiel** [comment]
Topic can not contain a dot in it's name. This is an old constraint, but it still holds. Dots are only allowed in group names.

**Comment by sslavic** [comment]
[Documentation](http://hermes-pubsub.readthedocs.io/en/latest/overview/data-model/#naming-convention) confirms Adam's expectation, while [code](https://github.com/allegro/hermes/blob/master/hermes-api/src/main/java/pl/allegro/tech/hermes/api/TopicName.java#L22) confirms Samuel's expectation.

Would it be a problem to actually support (at least one) dot in topic name?

**Comment by samuel-beniamin** [comment]
Is it possible to allow it. And if not, could the message be more clear and expressive.

**Comment by adamdubiel** [comment]
You are right, this part of code says something else, i would have to dig in to say why is it so. Anyway the important part is - due to group/topic naming convention there is currently no way to support dots in topic names. I guess if we fix the regex and fail fast, the message will be expressive :)

**Comment by sslavic** [comment]
It would be possible to allow dot in topic names as well, if TopicName.GROUP_SEPARATOR was changed to be something else than a dot, e.g. a hash character #. Would that be possible?

**Comment by sslavic** [comment]
Ah, Kafka doesn't allow it https://github.com/apache/kafka/blob/trunk/core/src/main/scala/kafka/common/Topic.scala#L29

**Comment by cristaloleg** [comment]
Looks like now it's allowed, hm https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/internals/Topic.java#L29

**Comment by ffosilva** [comment]
Remember to not use both '.' and '_' simultaneously.
https://github.com/apache/kafka/blob/2.3.0/core/src/main/scala/kafka/admin/TopicCommand.scala#L147-L148

**Comment by druminski** [comment]
Closing it. Hermes doesn't allow to use dot in topic name and in UI it's validated now.
