### ISSUE TITLE
Sporadically losing messages

### ISSUE THREAD

**Issue by gamefundas** [allegro/hermes#576]
Strangely we noticed today that some of our messages were lost after they were successfully posted to frontend. Elasticsearch didn't show any entry for for the lost message ID's, both sent and received had no entries. About the same time other messages published were received successfully. In terms of system load we may be having 30-40 messages per second. 

Looking at logs across, frontend, zk, kafka and consumer for that time window didn't reveal anything. It's a mystery what happened to those few messages in a spread of 2-3 hours. It's unclear at this point as to how many messages were lost but at least a handful of them were identified. 

Have you noticed or come across anything like this in your setup? Currently the plan is to restart all the modules and monitor this tomorrow to see if it occurs again. Our recon process is also now enabled to spot the instances of these anomaly. 

Please let us know if anything else comes to your mind.

**Comment by adamdubiel** [comment]
Were there any restarts/malfunctions of Kafka brokers at the time? What is the ACK level on the topic (leader vs all)?

**Comment by adamdubiel** [comment]
Did you manage to diagnose the problem? From our experience ACK-ALL makes all problems go away, but it's Kafka specific behaviour, not Hermes. Let us know, i will close the issue for now, but don't hesitate to repoen it.

**Comment by gamefundas** [comment]
We didn't have sufficient logging to investigate this but it seems we have ACK-Leader configuration. Doesn't ACK-ALL add a overhead to message delivery? Perhaps its a matter of speed vs reliability.

**Comment by adamdubiel** [comment]
ACK-ALL (or ack -1 in Kafka naming) means that all brokers that replicate the topic need to send ACK that the message has been persisted. This of course has a big effect on latency - try it for yourself. However Hermes with its buffers somehow mitigates it, so you should not see times larger than 65ms. Hermes buffers anything that takes longer to ACK and just waits for it, but the client gets the confirmation quicker.

Real life example: before we beefed our Kafka cluster, it took Kafka ~1 second to acknowledge the ACK-ALL message. However our users seen only 65ms of it, afterwards they received the `202 Accepted` status code, which they understand as "it's gonna be ok". Messages wait in Hermes buffer the remaining time, till Kafka accepts (or not - then Hermes retries the message). All in all we never once had a problem of missing messages in ACK-ALL mode.
