### ISSUE TITLE
Schema repository in vagrant

### ISSUE THREAD

**Issue by chemicL** [allegro/hermes#601]
After removing zookeeper as an AVRO schema storage option (current develop branch), we are missing a way to interact with AVRO schemas in vagrant during development.

The Configs.java contains an entry

```
SCHEMA_REPOSITORY_SERVER_URL("schema.repository.serverUrl", "http://localhost:8888/schema-repo/")
```

However, no schema-repo is present in vagrant. We should set up a basic schema-repo (https://github.com/schema-repo/schema-repo) in vagrant so that development goes smoothly.

**Comment by druminski** [comment]
Closing it as we have schema-registry in docker files now.
