### ISSUE TITLE
Flush missing-resources metric as snapshots are taken and reported

### ISSUE THREAD

**Issue by sslavic** [allegro/hermes#606]
E.g. consumer workload stats like missing-resources metrics are collected as histogram, and for missing-resources histogram stats to be usable for alarming (that consumers are under capacity) they have to be flushed once snapshot is taken and reported. At the moment that's not the case so neither min nor max missing-resources histogram stats are not usable.

**Comment by sslavic** [comment]
As implementation detail, maybe consider using HdrHistogramResetOnSnapshotReservoir from https://bitbucket.org/marshallpierce/hdrhistogram-metrics-reservoir

**Comment by sslavic** [comment]
Note that once missing-resources histogram reservoir is reset on snapshot, [report.period](https://github.com/allegro/hermes/blob/master/hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java#L171) has to be set to higher value than [consumer.workload.rebalance.interval.seconds](https://github.com/allegro/hermes/blob/master/hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java#L142) otherwise reporter could report 0 missing-resources even though consumers cluster is overloaded.

**Comment by adamdubiel** [comment]
I'm closing this since we will keep those values in gauge instead of histogram.
