### ISSUE TITLE
"jsonToAvroDryRun" flag deos not work properly

### ISSUE THREAD

**Issue by pszymczyk** [allegro/hermes#613]
When event is not compatible with schema and dry run mode is enabled sending requests failing with:

```
Async POST request for "service://hermes/topics/pl.allegro.product.index.v2.allegroProductMappingAdded" resulted in 408 (Request Time-out); invoking error handler
```

**Comment by dankraw** [comment]
OK, just tested it.
Actually `jsonToAvroDryRun` works but for valid Hermes-schemas only (containing `__metadata` field). 
For Hermes-invalid schemas (that don't contain `__metadata` field), when message is OK (the JSON body can be successfully converted to Avro using this schema), still a `WrappingException` is thrown while we catch `AvroConversionException` only. There is no error log for such case.
