### ISSUE TITLE
NotificationsBasedSubscriptionCache.onSubscriptionRemoved not removing subscriptions with non-null MessageFilterSpecification

### ISSUE THREAD

**Issue by sslavic** [allegro/hermes#617]
NotificationsBasedSubscriptionCache.onSubscriptionRemoved doesn't actually remove Subscription once subscription ZK node is deleted, if subscription has filters defined.

Subscription overrides equals and one of the fields used is filters (see [here](https://github.com/allegro/hermes/blob/master/hermes-api/src/main/java/pl/allegro/tech/hermes/api/Subscription.java#L231)). [MessageFilterSpecification](https://github.com/allegro/hermes/blob/master/hermes-api/src/main/java/pl/allegro/tech/hermes/api/MessageFilterSpecification.java) does not override equals.

Because of this [NotificationsBasedSubscriptionCache](https://github.com/allegro/hermes/blob/master/hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/subscription/cache/NotificationsBasedSubscriptionCache.java#L45) will not remove deleted subscriptions with filters defined from the cache, and  [SelectiveWorkBalancer](https://github.com/allegro/hermes/blob/master/hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/selective/SelectiveWorkBalancer.java#L25) will never see subscription as removed so consumer thread for deleted subscription will remain to be running and assigned for subscription until hermes-consumers app is restarted.

Please have this fixed.

Maybe just comparing [here](https://github.com/allegro/hermes/blob/master/hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/subscription/cache/NotificationsBasedSubscriptionCache.java#L45) by key and not also by value would work. If that would be unsafe, then maybe overriding equals in MessageFilterSpecification would work, or improving Subscription equals override to be simpler (e.g use id and/or version information).

Please also consider logging a warning in that NotificationsBasedSubscriptionCache.onSubscriptionRemoved method, if Map.remove call returns false.

**Comment by wojtkiewicz** [comment]
Thanks, I fixed this here #616
