### ISSUE TITLE
ZookeeperGroupRepository should ensure groups path exists before creating group

### ISSUE THREAD

**Issue by sslavic** [allegro/hermes#632]
Currently hermes-consumers has more tight dependency than needed on hermes-management being started first to initialize some common paths in ZK, like groups ZK node.

Because of this all (system) integration tests have to either start hermes-management as well, or have ugly call to initialize groups path.

To make this dependency bit more loose,  it would be enough in ZookeeperGroupRepository.createGroup to ensure groups path exists before creating the group itself.

**Comment by druminski** [comment]
Closing it, as start order of hermes modules is not relevant right not. You can start any module in the first place and it will work correctly.
