### ISSUE TITLE
ConsumersProcessSupervisor is not killing any consumer process

### ISSUE THREAD

**Issue by samuel-beniamin** [allegro/hermes#636]
In a recent commit [here](https://github.com/allegro/hermes/commit/da588df560783dc7d07030a0670bce6cdfc2fc17#diff-937eef0841e89c63e742f16bb280677b) for gracefully shutting down consumers, the `ConsumerProcessSupervisor` has been changed to check if there is a `ConsumerProcess` for given subscription before attempting to interrupt that `ConsumerProcess`. 

That new condition is mistakingly not allowing any consumer process to be interrupted [here is the condition](https://github.com/allegro/hermes/blob/master/hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/process/ConsumerProcessSupervisor.java#L144), I believe the condition should be reversed.

**Comment by wojtkiewicz** [comment]
wow, thanks

**Comment by samuel-beniamin** [comment]
Would you please also include a test case for it 👍

**Comment by wojtkiewicz** [comment]
We don't have at the moment any api that would allow us to test such a thing easily. Thats why we haven't notice this bug earlier. I will test this manually for now and think about some api for debugging supervisor later.

**Comment by samuel-beniamin** [comment]
Thanks.

**Comment by druminski** [comment]
Described problem does not occur anymore
