### ISSUE TITLE
Introduce consumers-workload.monitor.running metric

### ISSUE THREAD

**Issue by sslavic** [allegro/hermes#641]
`ConsumersRuntimeMonitor` is reporting `consumers-workload.monitor.missing` and `consumers-workload.monitor.oversubscribed` metrics already. Please consider reporting `consumers-workload.monitor.running` metric as well.

Knowing how many there are running `ConsumerProcess`es and capacity per instance, one can alarm/notify sooner and act (increase capacity or whatever appropriate), before problem actually happens (cluster is over capacity which is signaled already by missing-resources metric).

**Comment by adamdubiel** [comment]
We actually use `threads` metrics for this, as it shows how many subscription threads are currently running, but you are right - it would be better to have it explicitly named in `consumers-workload` metrics.
