### ISSUE TITLE
Kafka zookeeper gives Error:KeeperErrorCode = NodeExists for /brokers/ids

### ISSUE THREAD

**Issue by sudarshan1989** [allegro/hermes#648]
I am using Kafka_2.11-0.10.1.0 gives this error if the kafka server is running in port 9002

**Comment by adamdubiel** [comment]
Looks like you are having problems with Kafka, not Hermes? If so, please head over to their mailing list or JIRA. If it is connected to Hermes somehow, feel free to reopen this issue, but also add bit more details - what you have done so far, version etc.
