### ISSUE TITLE
Failed consumer process despite existing assignment doesn't get recreated

### ISSUE THREAD

**Issue by chemicL** [allegro/hermes#651]
A consumer process can fail and will not be re-created if the balancing algorithm is stable, i.e. the assignments don't change for the given subscription.
There are two things I observed
- inconsistencies in subscription cache and subscription repository can cause the starting consumer to fail.
- when the `ConsumersRuntimeMonitor` notices a missing consumer for an assignment, it does not signal recreation of the failed consumer.

Therefore, the following things can be done to mitigate the problem long term:
- investigate inconsistencies, such as Curator reporting a missing node for a Subscription we know exists, and perhaps reading from the cache instead of repository in some cases.
- make subscription cache behave like a cache, meaning that if we don't have the subscription info in cache, we fetch it from zookeeper.
- have `ConsumersRuntimeMonitor` issue signals to re-create a failed consumer.

**Comment by druminski** [comment]
+1 for this issue as I am observing it right now on prod environment and have to restart consumers manually

**Comment by dankraw** [comment]
+1 for self-healing of failed consumers.

**Comment by abbi-gaurav** [comment]
@chemicL 
I am also seeing a similar issue intermittently. Were you able to reproduce it consistently?
If yes, could you please share the steps?

**Comment by chemicL** [comment]
@abbi-gaurav I'll submit a PR which includes an integration test showcasing how the problem happens (creating consumer throws an exception). Hopefully the issue will be resolved by this solution.
From the observations I made it seemed that the problem was caused only when creating the consumer threw an exception so I am fixing this situation for now.
