### ISSUE TITLE
Updating existing subscriptions 

### ISSUE THREAD

**Issue by hikrrish** [allegro/hermes#662]
Is there a way to update the existing subscription, if in case I want to modify the subscription policy ?

Thanks

**Comment by adamdubiel** [comment]
Yes, simply send a PUT to subscription endpoint (`/topics/X/subscriptions/Y`) with json containing new field values like:

```
{
  "subscriptionPolicy": {
    "requestTimeout": 60000
  }
}
```

**Comment by hikrrish** [comment]
I tried this, however the subscriptions were not getting updated so I ran the delete /create for this, which works well for me. Now, when a subscription is created, I noticed it remain in pending state unless I restart consumer application. So, are we expected to restart consumer for new subscriptions ?
Also noticed pending subscriptions delivering messages, so just wanted to understand the PENDING state of subscription.

**Comment by adamdubiel** [comment]
No, no restart needed when adding/deleting/modyfying existing subscriptions. The PUT i sent you works, it is tested etc etc. What are the effects for you? Do you get 2xx when sending it?

PENDING means that no consumer started to work with this subscription, but this status indicates trouble. Normally subscription goes from pending -> active in seconds.

**Comment by hikrrish** [comment]
Yep it works, the only issue I noticed is I need to restart consumers to make the subscription active

**Comment by hikrrish** [comment]
though, subscription in pending state also serve

**Comment by druminski** [comment]
Subscription policy can be updated on the fly. Consumers restart is not required.
