### ISSUE TITLE
Support pluggable retryable & interruptable handling of filtering exceptions

### ISSUE THREAD

**Issue by sslavic** [allegro/hermes#668]
Currently, if filter throws an exception, message will be considered as filtered out and committed to Kafka.

We have a filter which has to make a remote call to decide whether message should be filtered out or delivered, and as consequence can fail for multiple reasons (timeouts, remote service temporarily not accessible, etc). In case filter throws an exception (can be java.lang.Exception or special Hermes FilteringException type but not any Throwable, so not Error like OOME) it would be nice to be able to plugin custom logic for handling exception - e.g. not to consider message as filtered.

It should be also possible in that condition (filter result of message is that message is not filtered out, yet exception/cause has been thrown) to retry filtering whole filter chain (and not only filter that failed), and retry using any guava-retrying options (so e.g. allow limiting on time, number of attempts, or no limit at all to retry endlessly).

ConsumerProcessSupervisor should consider ConsumerProcess which is actively filtering as healthy.

ConsumerProcessSupervisor should be able to shutdown ConsumerProcess which is actively filtering a message (e.g. as reaction to assignment change, for consumer process for given subscription to relocate to another hermes-consumers node), and that should not cause message loss or message to be committed (when consumer is relocated on another node it should receive same message and try consuming/filtering/sending it again).

**Comment by druminski** [comment]
Closing this issue as it was not addressed for over 5 years, so assuming it is not so important. We can back to it in the future, when it will be needed.
