### ISSUE TITLE
Consumer not able to deliver messages 

### ISSUE THREAD

**Issue by hikrrish** [allegro/hermes#706]
@adamdubiel 

We have a 3 node cluster and on one of the nodes and we say this error on one of the nodes today morning.
2017-02-03 4.575 ERROR p.a.t.h.c.c.r.k.KafkaSingleThreadedMessageReceiver - Error while reading message for subscription {s}
org.apache.kafka.common.errors.SerializationException: Error deserializing key/value for partition abc at offset 73642
Caused by: java.lang.IllegalArgumentException: null
        at java.nio.Buffer.limit(Buffer.java:275)
        at org.apache.kafka.common.record.Record.sliceDelimited(Record.java:392)
        at org.apache.kafka.common.record.Record.value(Record.java:368)
        at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:625)
        at org.apache.kafka.clients.consumer.internals.Fetcher.parseFetchedData(Fetcher.java:548)
        at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:354)
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1000)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:938)
        at pl.allegro.tech.hermes.consumers.consumer.receiver.kafka.KafkaSingleThreadedMessageReceiver.next(KafkaSingleThreadedMessageReceiver.java:92)
        at pl.allegro.tech.hermes.consumers.consumer.receiver.kafka.FilteringMessageReceiver.next(FilteringMessageReceiver.java:37)
        at pl.allegro.tech.hermes.consumers.consumer.SerialConsumer.consume(SerialConsumer.java:91)
        at pl.allegro.tech.hermes.consumers.supervisor.process.ConsumerProcess.run(ConsumerProcess.java:59)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

I tried restarting consumers, but no luck

**Comment by adamdubiel** [comment]
`org.apache.kafka.common.errors.SerializationException: Error deserializing key/value for partition abc at offset 73642`

This looks like data corruption in Kafka, i remember we had this kind of issues couple years back because of snappy, but as i said it was a long time ago on Kafka 0.8.1.1.

**Comment by hikrrish** [comment]
We found a link on stackoverflow saying this may caused due to different producer library than what actually kafka is using our kafka is kafka_2.11-0.10.0.1.jar on examining  we found that hermes-frontend is bringing an old version of kafka client, for now we have excluded to see if that works.

We have seen this issue for a single message in a span of 3 months after upgrade

 <groupId>pl.allegro.tech.hermes</groupId>
               <artifactId>hermes-frontend</artifactId>
               <version>0.10.0</version>
 -             <exclusions>
 +              <exclusions>
                   <exclusion>
                       <artifactId>kafka-clients</artifactId>
                       <groupId>org.apache.kafka</groupId>
                   </exclusion>
               </exclusions>
           </dependency>
 +          <dependency>
 +             <groupId>org.apache.kafka</groupId>
 +             <artifactId>kafka-clients</artifactId>
 +             <version>0.10.0.1</version>
 +         </dependency>

**Comment by adamdubiel** [comment]
While indeed we have some ancient version defined in `hermes-frontend` `build.gradle` (0.8.x), it is shadowed by `hermes-common`:

```
./gradlew dependencies

+--- org.apache.kafka:kafka-clients:0.8.2.0 -> 0.10.0.1 (*)

```

So this should not be the source of your problems.

**Comment by adamdubiel** [comment]
Of course we will remove this ancient dependency, don't know why it is still there.

**Comment by hikrrish** [comment]
Yes, we are also not sure after exclusion we are using kafka-clients-0.10.0.1.jar instead of 8.x version

**Comment by adamdubiel** [comment]
You were using it all the time - 0.8.x was shadowed and replaced by 0.10.0.1 if you build the artifact using Gradle.

**Comment by adamdubiel** [comment]
PR for removing this dependency: #716

**Comment by gamefundas** [comment]
@adamdubiel  we were unfortunate to get this error again in two of the topics just before the holiday weekend. Spent a great deal of time fixing this on production which involved wiping out all the messages for those topics.

Anything in particular we should be careful about with the payloads. In our case its plain Json that is getting serialized by Jackson. In Hermes is it simply StringSerializer on both the publisher and subscriber end? Any sort of compression or encoding that is done to the payload that might cause the Kafka client deserializer to go nuts?

We also couldn't figure out how to skip those 2 bad offsets and recover. Ended up expiring the topic prematurely to wipe out the messages. If your team follows anything better it would be good to know.

**Comment by adamdubiel** [comment]
1) Are you using any kind of compression? As i said before, we were hit by this issue only once, in old versions of Kafka and Snappy.

2) Skipping messages: i would note partition and offset of corrupted messages (they were probably all over the logs), stop subscriptions and then manually skip them either by modifying ZK records or by creating simple python/java program to change offset using Kafka drivers..

**Comment by gamefundas** [comment]
Thanks @adamdubiel for your response.

Few observations so far, 

Couple of issues here,

1. Deserialization issue - figured out this one is again our CI failing to package the new kafka client. It was using the 0.8 version. A miss on our end to verify this in bundled jar. At least explains the error above.

2. Intermittent message loss - This started happening soon after we got rid of the data in the bad topic. It seems to appear like #576. Its happening for the same topic though and messages weren't found persisted in Kafka. Querying kafka revealed that it doesn't have any offsets for the lost message. Could easily find all the other delivered messages. Went through each partition and confirmed that all offsets were consumed correctly.

But couldn't find any trace of the lost message. No errors in frontend, consumer, kafka or zk. Frontend logs report that the message was published to Kafka successfully. We are using ACK all so I am thinking this should have been persisted. 

"unclean.leader.election.enabled" publisher property is defaulted to false in our Kafka 0.10, but don't see any leader elections change during this time. 

The only other factor in the mix is the 0.8 Kafka client version which we plan to fix this weekend. But that doesn't seem to explain the message loss. The last time we had this problem we had to recreate the entire stack zk kafka and hermes fresh. Trying to avoid it. :)

Anything that we may be missing here from your experience.

**Comment by gamefundas** [comment]
This is not a Hermes issue, so I am going to check on StackOverflow to see if I get some Kafka inputs on this.

In publisher configuration, I see that #186 takes care of "unclean.leader.election.enabled" and we can confirm this in our topics.

However its hard to tell if ACK "all" is effective, The property we are using in the topics is 
{
     "ack": "ALL",
}

Is this supposed to be in all caps, "ALL" or "all" as some places in the documentation indicates lowercase. Or case doesn't really matter?

**Comment by adamdubiel** [comment]
Internally ack level is Java enum, so in api it is `ALL` in uppercase. There are actually separate metrics for ack `LEADER` and `ALL` in Hermes, as there are two separate Kafka client instances with separate buffers to handle different kinds of traffic. 

If you are not sure if your topics really use the `ALL` client, you can take a look at latency metrics, which are split between clients and are described [in docs](http://hermes-pubsub.readthedocs.io/en/latest/deployment/metrics/#latency). For `ALL` topics you should have metrics only in the all tree.

As for the problem with message loss. This started occurring after you cleaned up corrupted messages? You could always enable message tracing, unless you already have everything in logs.

**Comment by gamefundas** [comment]
Nice, there is a way to confirm the acknowledgement level using Metrics. Will try this one out.

Yes message loss started after the incident where Kafka consumer couldn't read couple of offsets. Once we cleared the topic then we started seeing sporadic loss of messages.
