### ISSUE TITLE
DC/OS integration

### ISSUE THREAD

**Issue by mmolimar** [allegro/hermes#725]
It'd be great to be able to deploy Hermes on DC/OS via its public universe. Have you thought about doing this?

**Comment by adamdubiel** [comment]
Although we run Mesos cluster in Allegro, i personally don't have much experience with DC/OS. I guess that could be a fun way to learn more, so while it is not on a priority list, it might be nice to do as an end-of-sprint project. Thanks for suggesting, we will make it happen :)

**Comment by mmolimar** [comment]
That sounds really great! ;-)
Looking forward to it

**Comment by adamdubiel** [comment]
Reopening till it happens

**Comment by pouledodue** [comment]
would be great

**Comment by druminski** [comment]
Closing it due to 4 years timeout.
