### ISSUE TITLE
Upgrade to Kafka 0.11 client API

### ISSUE THREAD

**Issue by sslavic** [allegro/hermes#798]
Please also consider getting rid of SimpleConsumer use - it's deprecated.

**Comment by adamdubiel** [comment]
Simple consumer is only used to read messages by timestamp. We should move to Kafka timestamps instead of reading messages on our own, but we introduced this feature before Kafka gave possibility to move offsets based on timestamp.

**Comment by druminski** [comment]
Closing as Hermes works on Kafka 2.0.0
