### ISSUE TITLE
New offset commiting mechanism with lag raporting

### ISSUE THREAD

**Issue by adamdubiel** [allegro/hermes#8]
Current offset commiting mechanism in extreme cases (quick output rate decrease) might lead to situations, when we commit events that might have not been sent. If sender is be okay - this is fine, but in case of any sender bugs, we will acknowledge unsent event.

This change might lead to situation, when lag is growing, as we don't commit messages. There should be some graphite metric (and log message) that we can observe and react.

**Comment by pjagielski** [comment]
in 0.7.2
