### ISSUE TITLE
jboss-logging Jar hell

### ISSUE THREAD

**Issue by adamdubiel** [allegro/hermes#807]
We have a pretty nasty instance of Jar hell in `hermes-management` (and probably other modules as well).

Undertow will not work with old versions of `jboss-logging` because `BasicLogger` interface lacks `debug(String, int)` method, which is called in Undertow method called by Spring Boot at startup.

`BasicLogger` comes from `org.jboss.logging:jboss-logging` artifact. However HK2 has it's own copy of this class (SIC!). It is not repackaged.. so in `org.glassfish.hk2.external:bean-validator` an old version of `BasicLogger` class exists, with same package and name as the original `jboss-logging` version. Rolling the dice, we can either load proper `jboss-logging` or tainted HK2 version of this class.

Maybe newer versions of HK2 have newer version of this class, but this actually makes me wonder if we should use this project at all. There are a lot more copies of classes in `org.glassfis.hk2.external` modules so there is no saying when it will blow up in our face once again.

**Comment by piotrrzysko** [comment]
Closing as we no longer use HK2.
