### ISSUE TITLE
Hermes Consumers should init fully when dependencies are not accessible and resume normal operation once dependencies are available

### ISSUE THREAD

**Issue by sslavic** [allegro/hermes#813]
Hermes consumers instances can turn to a zombie - it can start, fail at initializing but not crash, e.g. if ZooKeeper is not accessible (UnknownHostException, ZK host not reachable) because of temporary network issues. The only way to recover from this state is to restart the instance, even if network issue is temporary.

At the moment one can make use of ConsumerHttpServer endpoints ( /status/health will say that the app is up but /status/subscriptionsCount will fail in the ZK not accessible case) and have orchestrator check consumer app instance liveness, and restart it if it's not alive after a timeout.

It would be better if Hermes Consumers would additionally init completely even when dependencies like ZooKeeper or Kafka are not available, and (if it doesn't get restarted by orchestrator) resume normal operation, reconnect to dependencies once they are available.

To achieve this, I guess it would help to refactor Hermes first to consistently use a proper DI, as planned in 1.0 roadmap.

**Comment by adamdubiel** [comment]
You can make Zookeeper Client more tolerant by playing with retries/delays options. I would rather fix healthcheck (`/status/health`). If ZK dies, Hermes will continue to work and retry the connection in background - this one we tested.
