### ISSUE TITLE
OffsetCommitter can get stuck with no longer valid offsets in OffsetQueue

### ISSUE THREAD

**Issue by sslavic** [allegro/hermes#815]
OffsetCommitter can get stuck committing invalid offsets in case OffsetQueue contains offsets to be committed which are no longer valid, outside of the range. This can happen for subscriptions that have fallen behind and get part of not yet delivered offset range deleted by log cleanup.

With auto.offset.reset configured to earliest or latest, KafkaConsumer.poll for such subscription will silently auto reset and it may even successfully deliver newer messages still on the topic, but because there is a gap between old from-deleted-range offsets in OffsetQueue, and newly committed from still valid range offsets, OffsetCommitter will keep on trying to commit old one(s) only, assuming gap will eventually be filled, which is wrong - deleted messages by log cleanup are lost for that subscription for good.

Related problem - KafkaConsumer.commitSync(offsets) will throw CommitFailedException not only when KafkaConsumer instance is no longer lead for TopicPartition in consumer group due to rebalancing but also when offset is invalid, and there seems to be no way at the moment (kafka-clients 0.11.0.0) to differentiate the reason of failure; therefore failed commit because offset is invalid cannot clean up invalid offsets from the commit queue.

Maybe KafkaConsumer instance could internally in Hermes always be configured to auto offset reset = none, to be able to detect invalid offset conditions in poll calls and then cleanup no longer valid offsets; if user configures Hermes Consumers to auto offset reset latest or earliest, that would have to be done "manually" in addition to invalid offset cleanup from OffsetQueue - find out appropriate latest/earliest valid offset, and commit that, or make OffsetQueue use that as last committed offset for TopicPartition and consumer group.

**Comment by druminski** [comment]
We have provided a lot of fixes in Hermes commit mechanism which addresses described problems. We also have plans for changing auto.offset.reset to earliest in #1081
