### ISSUE TITLE
ConsumerProcessSupervisor throws NPE when processing any Signal still in taskQueue for killed ConsumerProcess

### ISSUE THREAD

**Issue by sslavic** [allegro/hermes#816]
E.g. if taskQueue includes kill and commit Signal for same assignment/subscription, processing of kill Signal removes ConsumerProcess from runningProcesses, and processing of commit Signal implemented in processSignal method with:

```
                case COMMIT:
                    process(signal).accept(signal);
                    break;
```

will fail with NPE, since `process(signal)` will return null.

Since processSignal has access only to current Signal being processed, so no access to rest of the taskQueue snapshot to be processed, maybe one way to fix this is in every process(signal) call to perform null check first, and only pass signal downstream to ConsumerProcess if null check passes, otherwise log a debug message that Signal was dropped.

**Comment by druminski** [comment]
Closing this issue as it should not occur anymore due to refactor of signals in hermes-consumers. Right now Hermes process `COMMIT` signal only when consumer is in running state.
