### ISSUE TITLE
Exception in hermes Consumers 

### ISSUE THREAD

**Issue by hikrrish** [allegro/hermes#820]
com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class pl.allegro.tech.hermes.consumers.consumer.rate.maxrate.MaxRate]

Version : 0.11.0

**Comment by gamefundas** [comment]
Duplicate of #825 
This one can be closed.

**Comment by adamdubiel** [comment]
Closing :)
