### ISSUE TITLE
Topic message preview in human readable form

### ISSUE THREAD

**Issue by druminski** [allegro/hermes#821]
Topic message preview in Hermes-console displays original message send on a topic. In JSON topics this feature works great, however in Avro topics displaying binary message on UI is not a good idea as the message is not readable. Example:

![screen shot 2017-09-21 at 15 05 37](https://user-images.githubusercontent.com/4473056/30697515-8d32ee94-9edf-11e7-9e39-219c4ac8a54b.png)

It would be nice to convert this Avro message to JSON before displaying it in Hermes-console.

**Comment by mictyd** [comment]
I'll try taking this one.
