### ISSUE TITLE
More descriptive response in case of incompatible message with schema

### ISSUE THREAD

**Issue by druminski** [allegro/hermes#822]
During publish on Hermes it would be nice to return a response describing why message is incompatible with schema, for example because of missing field or wrong type. These information are available in an exception which Hermes logs so it should be easy to set them also in the response.

This small improvement will simplify using Hermes by our developers, especially on dev environment .

**Comment by janisz** [comment]
I'll take this.

**Comment by janisz** [comment]
I think it's undoable. Exception has no information if task has incompatible schema https://github.com/allegro/json-avro-converter/search?utf8=%E2%9C%93&q=%22new+AvroConversionException%22&type=
