### ISSUE TITLE
Remove inflight metric from Zookeeper

### ISSUE THREAD

**Issue by adamdubiel** [allegro/hermes#832]
There is an inflight counter that we keep in Zookeeper. This metric shows how many messages are currently kept in memory for each subscription. However we do not need the exact number, just an estimate, so moving this counter to "normal" metrics and changing it into gauge would limit the amount of ZK writes (and nodes).

**Comment by adamdubiel** [comment]
Before removing inflight metric from Zookeeper we need to fix [ActiveConsumersCounter](https://github.com/allegro/hermes/blob/1bacaf2ecb5d76a998f765acd9c35d6930b9e7c8/hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/ActiveConsumerCounter.java), which uses `inflight` nodes to count number of Consumers that own the subscription. It could use `consumers-workload` algorithm registry instead, but to do this we have to start removing the old `mirror` algorithm.

**Comment by jewertow** [comment]
Resolved in #1097
