### ISSUE TITLE
Question on Consumer - Retry on failure

### ISSUE THREAD

**Issue by gamefundas** [allegro/hermes#842]
I am not clear on what the behavior is in case of subscriber responding with a 503. The document talks about this but perhaps its just me I didn't understand well. 

My understanding and few questions below,

2xx - quite simple, treated as success
4xx - treated as failure and retried using back pressure only if retryClientErrors is set to "on"
5xx - treated as failures and retried using back pressure (couldn't understand what is the case with 503, with NO retry-after header) - Are we saying 503 has a special custom backoff provided by the subscriber header, otherwise its same as 5xx?

About TTL - the hard limit of 2 hours - Does this mean, the maximum a message will be tried for redelivery is 2 hours and it cant be configured to wait longer than this?

Also in any way Hermes consumer can be tweaked to behave differently for a specific Http response code?

Thanks
Andy

**Comment by adamdubiel** [comment]
You got everything right, let me clarify on 503.

503 *without* `Retry-After` header behaves just like a normal 5xx, meaning retries & back pressure kicks in.

503 *with* `Retry-After` means, that we will wait at least N seconds (value provided in Header) before we will retry. This also has no effect on back pressure algorithm.

2h of TTL - this is put inside the code directly, but i see no problem in making it configurable. 2h works for us.

How would you like to tweak it? 503 and `Retry-After` are actually part of HTTP specs :)

**Comment by gamefundas** [comment]
I had another team subscribing to one of our topics where they wanted us to not retry at all in case of a specific HTTP response code. Eg 408.

**Comment by adamdubiel** [comment]
I suspect you want to retry on all 4xx except for 408? Is there any rationale why? Does it have to do with HTTP RFC?

**Comment by gamefundas** [comment]
Its HTTP 412 in fact, so in this case the subscriber is referring to a scenario where the payload was received earlier and a duplicate is being redelivered. This can be hermes/kafka redelivering the message due to some outage/failures or the publisher sending the same payload again.

The subscriber wants to indicate that a precondition was met and the duplicate message is ignored through a 412 response.

**Comment by adamdubiel** [comment]
This sounds perfectly reasonable - if you care to create PR, we would definitely merge it :)

**Comment by gamefundas** [comment]
Will raise a PR for this.
