### ISSUE TITLE
Add option to trace only DISCARDED messages

### ISSUE THREAD

**Issue by adamdubiel** [allegro/hermes#915]
Currently enabling message tracing results in sending full trace (from Frontend and Consumers) to trace storage. Some of our clients are only interested in DISCARDED events, so we would like to have option to send only those.

Currently for each message we send traces:

* INFLIGHT
* PUBLISHED
* ERROR
* SENT
* DISCARDED
* FILTERED

With a proper flag set on subscription, we would send traces only for DISCARDED and ERROR.

**Comment by mictyd** [comment]
I'll take it

**Comment by adamdubiel** [comment]
Noooooo :) This is already closed by #918 . Closing it now :)
