### ISSUE TITLE
Accepting "schema-version" (lowercase) header

### ISSUE THREAD

**Issue by dankraw** [allegro/hermes#917]
Currently we accept only single header as the one containing Avro schema version (`Schema-Version`). Unfortunately, this will not work with http/2 clients, as all headers are lowercase words. 
We should allow defining a list of acceptable header names.

**Comment by adididas122** [comment]
Lower case in headers is not a problem. Headers extracting is case-insensitive. https://github.com/allegro/hermes/blob/8e06bfe8ab03d9ad4f1f253c5b6f0a6b4e2f6996/hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/message/MessageFactory.java#L116

**Comment by dankraw** [comment]
@adididas122 could you write a simple test for that? it might be helpful when upgrading undertow.

**Comment by adididas122** [comment]
Test added in https://github.com/allegro/hermes/pull/919.

**Comment by dankraw** [comment]
the test in #919 is now merged. thanks
