### ISSUE TITLE
Quick start links to RequestBin which was closed

### ISSUE THREAD

**Issue by pwolaq** [allegro/hermes#948]
[This section](https://hermes-pubsub.readthedocs.io/en/latest/quickstart/#publishing-and-receiving-messages) of the documentation mentions that `http://requestb.in/1isy54g1` can be used as example of subscription endpoint. 

However, this website does not work and according to the [info on the Github](https://github.com/Runscope/requestbin#readme) it was shot down about 7 months ago.

**Comment by cristaloleg** [comment]
Good catch. There are a lot of alternatives for RequestBin, just a few of them:
- [requestbin(as a product)](https://requestbin.fullcontact.com)
- [beeceptor](https://beeceptor.com)
- [mockbin](http://mockbin.org)

We need to select one of them.

**Comment by druminski** [comment]
We should peek and use some reliable mock endpoint as requestbin deletes mock after some time.
