### ISSUE TITLE
Remove the consumer inflight messages distributed counter

### ISSUE THREAD

**Issue by dankraw** [allegro/hermes#981]
Consumers report the number of messages being inflight to a different zk node that all other metrics (`/hermes/consumers/<node>/group/..topic/../subscriptions/.../metrics/...`).
I believe we even don't use this path at all.
Unfortunately the path is hostname-dependent and leaves a lot of rubbish in zookeeper.

IMHO we should get rid of it as inflight is being reported to graphite anyway.

see: `ZookeeperCounterStorage`

**Comment by dankraw** [comment]
OK, it's used by the "strict" max rate algorithm (which is deprecated).
It was used to get the number of active consumers.

**Comment by dankraw** [comment]
The other option, is not to set this path for consumers not running in 'strict' mode.

**Comment by spooz** [comment]
isnt is it connected? https://github.com/allegro/hermes/issues/832 :)

**Comment by dankraw** [comment]
@spooz yes, exactly :)
