### ISSUE TITLE
[Question] Max message size

### ISSUE THREAD

**Issue by gamefundas** [allegro/hermes#987]
We recently ran in to few rejections due to payload exceeding max message size. Is this a configuration that's controlled on Hermes topic level or on the Kafka side?

Saw few issues logged around this but didn't get a clear answer. Seems like we need to configure or manage on the Kafka side but thought I will will run it with you guys before making the change on our production servers.

Thanks
Andy

**Comment by dankraw** [comment]
It's controlled by the brokers and configured in kafka.
Additionally max message size can be set to a specific value per topic:
https://github.com/allegro/hermes/blob/bee4a59a9935518bc097d4c584a8ea288a86404f/hermes-api/src/main/java/pl/allegro/tech/hermes/api/Topic.java#L36

Hermes frontends may do the message size validation before sending them to brokers:
```
frontend.force.topic.max.message.size=true
```

**Comment by gamefundas** [comment]
Thanks @dankraw this helps.
