### ISSUE TITLE
Clean way of deleting or updating topics

### ISSUE THREAD

**Issue by gamefundas** [allegro/hermes#988]
Does Hermes support deleting or updating topics? I am thinking the answer is no as there is no API that talks about this. 

Would like to know what's a good strategy to follow here? Since Hermes is aware of the topics and deleting in Kafka/Zk directly may cause undesirables.

Looking for a cleaner solution to document in our SOP's as there are several unused topics in production that we could get rid of. Also the team has been creating new topics as a workaround instead of updating existing ones.

**Comment by dankraw** [comment]
Hi, there are such APIs in the management module (updating, removing topics):
https://hermes-pubsub.readthedocs.io/en/latest/user/permissions/#ownership-and-permissions
https://github.com/allegro/hermes/blob/master/hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/TopicsEndpoint.java#L105

Option for removing topics should be enabled in magangement's properties:
https://github.com/allegro/hermes/blob/bee4a59a9935518bc097d4c584a8ea288a86404f/hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/TopicProperties.java#L12

**Comment by gamefundas** [comment]
Thanks @dankraw will try this out. We are using an older version of Hermes, so will check the API to see if was available during that time.

**Comment by druminski** [comment]
Closing this issue as Hermes allows to delete topics.
